### ISSUE TITLE
Disable respawn button

### ISSUE THREAD

**Issue by adios113** [blackwatchint/blackwatchint#100]
During the meeting on 29.11.2015 we decided to disable the respawn button in the templates.

**Comment by adios113** [comment]
Changes applied to the base template on Virtual Reality Map:
https://github.com/blackwatchint/blackwatchint/commit/f719e41259700f214f4c404e4ad787424bd35304

Needs to be changed on the other maps as well, since the description.ext file is different for each map.

**Comment by adios113** [comment]
Applied to the templates files trough many single commits.

**Comment by ShiFoo** [comment]
Committed to master
