### ISSUE TITLE
F.A.T.A - Federally Administrated Tribal Areas

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/blackwatchint#105]
This map was removed in a prior modpack and is to be reintroduced with the next modpack update.

**Download:** http://www.armaholic.com/page.php?id=22057

**Comment by Fourjays** [comment]
Keep this part of the description in mind when compiling this for the modpack:

*To be able to use this map properly in Arma 3 while using All In Arma the ponds from the original map had to be removed.
So, if you wish to use this in Arma 3 with AIA you should download and install this version instead: Arma3 AIA compatible version (128MB).*

As a result, I want you to give this a test when compiling it into the modpack to make sure it is still good.

**Comment by TheGrandVizier** [comment]
Uploaded to repo

**Comment by wingatex** [comment]
Works fine passes all checks

**Comment by TheGrandVizier** [comment]
In our previous experience with this map we had unconfirmed reports of AI shooting through a couple of buildings in the center of Tottah.
I'd like us to try and pay attention to it this time around. Once we get one such report we should investigate and isolate the location. Possibly we can manually fix it by adding specific objects (concrete walls/barriers when / if we find such locations.

**Comment by Fourjays** [comment]
Committed to the test repository and ready for deployment.
