### ISSUE TITLE
Research available AI mods

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/blackwatchint#106]
Need to research the variety of AI mods to determine what options are available for possible inclusion.

All AI mods we look at must be tested on a number of fronts:
 - AI behaviour (individually and grouped)
 - Battlefield tactics (group movements on the field)
 - Compatibility with mission styles
 - Compatibility with modpack
 - Performance
 - Stability

**Comment by ShiFoo** [comment]
- Editor-only or also usable in Zeus

**Comment by adios113** [comment]
Overall research on AI, both as a mod and a mission script.

* VCOM-AI - Currently the most advanced AI mod there is in Arma 3. Requires a lot of performance from either server or zeus (that's why we got rid of it last time), but maybe it was just a buggy version? Who knows...

* ASR-AI - Good quality, combat enchancing mod, customizable, we had it running on the server for a longer time, but guys were having issue swapping the difficulty bar of the AI.

* b-combat - AI Mod aiming to enchance SINGLE PLAYER performance. Not MP compatible.

**Comment by ShiFoo** [comment]
*but guys were having issue swapping the difficulty bar of the AI.* this might a locality issue. If a Zeus spawns a unit, he owns it. I can imagine for an AI mod work properly, the server needs to be owner of it. This could potentially create a conflict: Zeus commands vs. AI Mod commands.

**Comment by Fourjays** [comment]
We had two separate issues with ASR. First was that when we originally had it it was installed server side only, so whenever a Zeus got disconnected all the AI got stuck at 100% difficulty (locality issue). Second was when we fixed that, the AI were incredibly unwilling to follow Zeus orders. There are a number of configuration options available for ASR though and it may work better with a headless client so it is worth looking at again.

I'll aim to test some AI mods as part of the 1.54 update tests this week.

**Comment by Fourjays** [comment]
Tried to do some testing of AI mods today. Unfortunately both ASR and VCOM require file patching to be enabled, which we are unable to do on the server being used for testing 1.54. May have a look at testing these once 1.54 is live on the configurable servers. However, file patching would still require members to change a setting clientside, which may not be desirable.

**Comment by ShiFoo** [comment]
Now that we have the 1.54 dedicated, file patching should not be an issue anymore, right?

Also:
Q: I just updated to 1.54 and am receiving a 'Script \userconfig\asr_ai3\asr_ai3_settings.sqf not found' error on launch.
A: Launch the game with file patching enabled (tick the option in the official launcher or add -filePatching to command line parameters). __This is only required in single player or on servers (not required on clients connecting to a multiplayer game).__

**Comment by Fourjays** [comment]
We're in full control now so can enable any options we like, although I'd like to know more about file patching before enabling it (there'll be a reason why it is an option).

Good that it doesn't actually require it clientside though. Makes it more practical to implement.

**Comment by ShiFoo** [comment]
As far as Abel and i can see file patching allows mods to replace standard BIS content. I am really curious on why the mod needs this enabled.

**Comment by Fourjays** [comment]
Closing as research is no longer relevant. ALiVE and ASR AI were added to the modpack with #247 and #248.
