### ISSUE TITLE
Sukhoi SU-34

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/blackwatchint#108]
**Description:**
This adds the SU34, a port from Arma 2.

All of this is a work in progress - It is not yet signed, as I may change the flight characteristics. Let's consider this a public alpha test.
It will never be even close to other planes like the SU-35 but I will do my best to make a working and useful plane.
The Textures are just quick n dirty. Keep in mind that they will change. 

Looking forward to feedback from you all

**Download:** http://www.armaholic.com/page.php?id=27961
**Size:** 34MB

**Comment by Kentersnoodlefactory** [comment]
Is this to see he general opinion on the plane and wait for a better release? Or do you want us to test it? Perhaps both!? :p

**Comment by Fourjays** [comment]
Was a mod suggestion so will need checking out as usual. The description isn't promising though.

**Comment by Kentersnoodlefactory** [comment]
It is pretty good, looks fine visually. Flies a bit funky at times, quite sensitive in pitch. But nothing terrible, i think it would be a nice addition considering that there are barely any opfor jets. This with a SU35 flanker and we are all set.

**Comment by Fourjays** [comment]
Gave this a test myself last night. Is visually of a pretty good quality (just have a very bright paint scheme, but that is accurate). Flying seems pretty decent. Needs a little bit of extra testing as the ones I was spawning didn't have any weapons loaded. That should be "fixable" via a tent hangar).

Some screenshots:
http://steamcommunity.com/sharedfiles/filedetails/?id=574426588
http://steamcommunity.com/sharedfiles/filedetails/?id=574426682
http://steamcommunity.com/sharedfiles/filedetails/?id=574427014
http://steamcommunity.com/sharedfiles/filedetails/?id=574427091
http://steamcommunity.com/sharedfiles/filedetails/?id=574426631

**Comment by Fourjays** [comment]
Checked the weapons/hangar. There is no support for the hangar, but there are many variants with different loadouts, some of which are missing missiles. I think they are simply trying to use weaponry that isn't available in our modpack.

Most of the aircraft do spawn with loadouts.

**Comment by Fourjays** [comment]
Rejected in the meeting on 13/12/15 due to quality concerns.
