### ISSUE TITLE
Panthera Map Update v3.3.6

### ISSUE THREAD

**Issue by ShiFoo** [blackwatchint/blackwatchint#109]
__Quote :__
Name Panthera itself comes from Slovenian history of "black panther" crest. Map itself is based on the real height data of Slovenia's Northwest part in Europe - named Gorenjska Region.
"Gora" in Slovenian means mountain and Gorenjska region (represented in Panthera) certainly lives up to its name being home to most of Slovenia’s biggest mountains, including the highest of them all – Triglav (three heads) standing at an impressive 2,865 metres. The Julian Alps and the beautiful Triglav National Park are the main features of the region – offering not just outstanding scenery, but a wealth of plant and animal life and an abundance of outdoor activities. It is also home to the unforgettable lakes Bled and Bohinj. It is almost impossible to decide which one you prefer – Serene Bohinj and its majestic mountain setting or fairytale Bled with its seventeenth century church on an island overlooked by a castle perched on a rocky outcrop.

__Changelog:__
new huge island: Savagia (inc. Felis Prison and couple of small settlements)
connected Savagia to Rubina with bridge
enabled dust effects for all terrain types
hangar height fix @ FOB Boriana
smoothened asphalt runways @ FOB Boriana
removed vegetation from two buildings in Rubina
removed tree from a road near Southeast Rubina gas station
rock fix at Vulcano Turk
removed lamppost from river in Arapovo
various other tweaks

__Download:__ http://www.armaholic.com/index.php?c=news&d=30
__Size:__ 239MB

**Comment by TheGrandVizier** [comment]
Correct Armaholic download link:
http://www.armaholic.com/page.php?id=27416

**Comment by TheGrandVizier** [comment]
uploaded to repo

**Comment by Fourjays** [comment]
Final checks done and it all looks good.

Has been committed to the test modpack repository and is ready for deployment.
