### ISSUE TITLE
ACE v3.4.1

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/blackwatchint#113]
ACE have released version 3.4.0. This version is expected to fix issues #10 and #112.

The changelog and download can be found on the ACE 3 Github: https://github.com/acemod/ACE3/releases

**Comment by ShiFoo** [comment]
I will provide a working Virtual Reality template by today evening so testing can start. While you are testing i will finish all other templates, so we can get this show on the road again.

**Comment by Fourjays** [comment]
ACE have released 3.4.1 already which fixes a number of issues already. The above download link is still valid.

**Comment by Fourjays** [comment]
Committed to the test modpack repository, awaiting deployment.
