### ISSUE TITLE
CBA v2.2.0.151130 Update for 1.54

### ISSUE THREAD

**Issue by ShiFoo** [blackwatchint/blackwatchint#119]
__Changelog:__
FIXED: 1.54 local keyword deprecation commy2, Nou
FIXED: Eden editor crash (#198) PabstMirror
FIXED: "Updating base class" RPT warnings robalo
FIXED: "No owner" RPT warnings commy2
FIXED: CBA_fnc_getPos robustness. (#187) commy2
FIXED: Unbound CBA key assignment display (#205) PabstMirror
ADDED: Multiplayer fireteam color synchronization (#185) BaerMitUmlaut
ADDED: Run-time extended event handlers: CBA_fnc_addClassEventHandler commy2
ADDED: Backpack and cargo item removal functions: CBA_fnc_removeBackpackCargo, CBA_fnc_removeBackpackCargoGlobal, CBA_fnc_removeItemCargo, CBA_fnc_removeItemCargoGlobal jonpas

__Link:__ http://www.armaholic.com/page.php?id=18767
__Size:__ 1MB

**Comment by TheGrandVizier** [comment]
Uploaded to repo

**Comment by Fourjays** [comment]
Update committed to the test modpack repository, awaiting deployment.
