### ISSUE TITLE
Create new platoon structure templates

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/blackwatchint#121]
New templates need to be made for all maps that feature our new platoon structure, as prototyped in #72.

**Comment by Fourjays** [comment]
This is currently pending a prototype comm card.

**Comment by ShiFoo** [comment]
Should this already implement a virtual Headless Client slot?

**Comment by Fourjays** [comment]
Plan is for headless client slots to be included in these templates, yes.

**Comment by Fourjays** [comment]
My tests with headless clients were very successful. I'm going to recommend that we implement the script version of Werthles Headless Kit (#135). I easily implemented it into one of our existing templates for testing (just the HC units, an SQF file and a link in init.sqf). It worked well in my extensive testing and includes a visual debug tool that mission makers would find useful.

I am going to setup the server to run up to two headless clients, so the new templates should include slots for both.

**Comment by ShiFoo** [comment]
Master template committed to branch. [BWI]Template to be distributed to other maps (excluded Esseker, Bastogne and Mogadishu).

__Ryan:__
Altis - Porto

__iFu:__
Porto - Zargabad + new maps.

**Comment by ShiFoo** [comment]
Rahmadi - Zargabad + VT5, Chern Winter, FATA and Sugar Lake templates incorporating the new platoon structure committed to branch.

**Comment by ShiFoo** [comment]
Comm Card: i can already display a picture. currently designing a "comm card picture" draft that can be reviewed at a meeting.

**Comment by ShiFoo** [comment]
Added comm card with last commit.

**Comment by ShiFoo** [comment]
All changes committed to 121. Closing.
