### ISSUE TITLE
BAF Update for 1.54

### ISSUE THREAD

**Issue by ShiFoo** [blackwatchint/blackwatchint#123]
v1.1
- Fixed insignia on uniform sleeves

__- Fixed bullet penetration and armour values on headgear__
__- Fixed bullet penetration and armour values on vests__
- Fixed accuracy and sight issues on the L16 Mortar
- Fixed inheritance issues with NVG
- Cleaned-up BAF faction names
- Improved vest base texture
- Added three berets (Royal Anglian, Royal Engineers and Mercian)

__Link:__ http://www.armaholic.com/page.php?id=29033
__Size:__ 333MB

**Comment by TheGrandVizier** [comment]
Uploaded to repo

**Comment by Fourjays** [comment]
A minor bug with this in 1.54 is the appearance of some "BASE MTP" units in Zeus. Confirmed as 1.54 specific by @TheGrandVizier.

**Comment by Fourjays** [comment]
Created a seperate issue for the additional units that are appearing (#162). Otherwise the update to 3CB BAF looks good.

Has been committed to the test modpack repository and is ready for deployment.
