### ISSUE TITLE
SU-35S Flanker E

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/blackwatchint#134]
**Description:**
After a few months of work on this mod Saul and me would like to share with the community our recent version of SU-35 S Flanker E mod. Saul has put in tremendous effort in to HD textures and updating the model. We have added nice set of features and improved the overall characteristics of the jet. It's still WIP on this one, with more time on our hands we will definitely try to update this awesome Russian aircraft mod. Features like fully Russian cockpit [markings and HUD] also refuelling and auxiliary fuel systems will be added latter on thru the development process. 

Su-35S is a OPFOR multirole fighter we decided to add since there still is massive demand for an adversary to F/A-18's. So what does this addon contains and what we are looking to implement in future.

**Download:** http://www.armaholic.com/page.php?id=24024
**Size:** 51MB

**Comment by Kentersnoodlefactory** [comment]
SU35S Flanker E: http://www.armaholic.com/page.php?id=24024

This is a very nice and detailed aircraft, it got a pretty nice cockpit. And it flies very nice, it models the movements of the thrust vectoring. It does fly like a airplane with that feature. It can be a bit sensitive in pitch but in general it is a nice aircraft and i think it would make a nice addition to the Russian hangar

**Comment by Fourjays** [comment]
The visual quality is very good, with a high quality model. It also features a pretty detailed and functional cockpit. It flies well and is very agile because of the thrust vectoring as @Kentersnoodlefactory said. All of the functionality looks good and it is equipped with a variety of weapons.

Screenshots:
http://steamcommunity.com/sharedfiles/filedetails/?id=574426885
http://steamcommunity.com/sharedfiles/filedetails/?id=574426821
http://steamcommunity.com/sharedfiles/filedetails/?id=574426770
http://steamcommunity.com/sharedfiles/filedetails/?id=574426726

**Comment by Fourjays** [comment]
Accepted in the meeting on 13/12/15.

**Comment by Fourjays** [comment]
Added to the test modpack repository, changes awaiting deployment.
