### ISSUE TITLE
Swap watch with microDAGR for all loadouts

### ISSUE THREAD

**Issue by ShiFoo** [blackwatchint/blackwatchint#136]
Non-programmables need the microDAGR which is currently not supported by the template. Every players with non-programmable needs to go into arsenal and grab one.

**Comment by DextroNC** [comment]
I made hosting modules for a comm card in the game and frequency setup for all elements. Does not mean people should not have the microDAGR, but it would liberate them from setting up their radio evertime.

https://www.dropbox.com/s/e695oln13h960qe/CommCardTemplate.zip?dl=0

**Comment by ShiFoo** [comment]
The frequencies module is not JIP compatible, we already tried it. It will work when you join the server before the mission starts but JIP / respawn / reconnects will have scrambled frequencies.

https://github.com/michail-nikolaev/task-force-arma-3-radio/issues/963
https://github.com/blackwatchint/blackwatchint/issues/72

**Comment by DextroNC** [comment]
True, but at least the people in time do not have to set frequencies, just as a suggestion.

**Comment by Fourjays** [comment]
Not sure I understand what the issue is here? Are MicroDAGRs simply missing from some loadouts or is there a problem with some templates that prevents them being added?

**Comment by ShiFoo** [comment]
All loadouts, especially the ones without a programmable radio, have watches instead of microDAGRs. So changing freqs required the player to go to the arsenal and grab one himself.

**Comment by Fourjays** [comment]
Wrong microDAGR added to loadouts. Will be fixed in the 121 branch.

**Comment by ShiFoo** [comment]
Correct microDAGR committed to 121 with https://github.com/blackwatchint/blackwatchint/commit/8905fbedd8ee96b03cc71647e03470e9a98db641 . Closing.
