### ISSUE TITLE
Fixed wing pilot loadouts missing earplugs, flashlight

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/blackwatchint#137]
During flight training pilots discovered they were missing earplugs and flashlights for map reading. The fixed wing pilot loadouts require earplugs and a flashlist (for map reading).

Lets also check that rotary pilots have these items.

**Comment by Fourjays** [comment]
The loadouts on the boards do have the correct gear, but these same loadouts are not being loaded at the start. Will be fixed in the next update.

**Comment by ShiFoo** [comment]
All pilot classes (blufor and opfor) should have a loadout specified in the init line with the new platoon structure in #121 . Closing
