### ISSUE TITLE
Kunduz pedastals are duplicated

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/blackwatchint#140]
The loadout pedastals at the spawn on the Kunduz template are duplicated on top of themselves and appear twice. Only one set of the duplicated pedesatls actually functions.

**Comment by Fourjays** [comment]
Should be naturally fixed when we re-do the templates for the new platoon structure.

**Comment by ShiFoo** [comment]
Obsolete because new Kunduz template committed with #121
