### ISSUE TITLE
Set G-Force values for pilot roles

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/blackwatchint#142]
All fixed-wing pilot slots should have a G-Force value defined on them to help prevent G-LOC. The code for doing so is as follows (where "pilot" is the unit):

```sqf
pilot setVariable ["ACE_GForceCoef", 0.75];
```

Rotary roles are to be left unaltered for now, but we may tune values for both in the future.

**Comment by ShiFoo** [comment]
committed with #121 / https://github.com/blackwatchint/blackwatchint/commit/938f09ada8ce3b0ace8f48bc74c5a868a348027d
