### ISSUE TITLE
C130 Variants

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/blackwatchint#143]
**Description:**
This addon adds some Lockheed C-130 Variants to Arma 3.
It is a port and expansion of the original Arma 2 C-130 and based on BIS APL Source Files.

Features:
- C-130 J (with/without Droptanks, Cargo Version, Tanker)
- C-130 H (with/without Droptanks, Cargo Version, Tanker)
- C-130 Coast Guard
- LC-130 
- LC-130 with skis and Jato
- Fat Albert with Jato 
- XFC/YMC-130H inspired variant
- A3 exhausts
- added A3 lights and position/collision lights
- working door & ramp animations
- copilot, flight engineer and load master
- firing from vehicles
- Jatos and Shrikes
- Landing on water (Floatplane)
- proxied Droptanks, Skis and Jato bottles (can be switched ingame via Triggers)

**Download:** http://www.armaholic.com/page.php?id=28024
**Size:** 50MB

Posted as a result of #131 for consideration in replacing USAF pack.

**Comment by Fourjays** [comment]
I've given this a go a number of times over the last week. RHS does include a single C130J, but compared to the C130s in this pack it flies poorly.

These C130s use an Arma 2 model but look of a very good quality. There is a large variety in this pack, with BLUFOR, OPFOR and civilian liveries. They all appear to function well with working cargo ramps. There are JATO/RATO, float and ski based variants that also appear to work as expected. The interiors are also all fully working and of a good quality.

Most importantly, they fly well. Short runways and dirt runways are not a problem, and the turning performance feels more accurate. On the downside, unlike the USAF Pack's C130s they don't include loadable cargo (without a mission script) and there's no AC-130 variant. I also had some trouble getting the float variant to sit in the water via Zeus.

A few screenshots:
http://steamcommunity.com/sharedfiles/filedetails/?id=574427146
http://steamcommunity.com/sharedfiles/filedetails/?id=574427208
http://steamcommunity.com/sharedfiles/filedetails/?id=574427276
http://steamcommunity.com/sharedfiles/filedetails/?id=574427520
http://steamcommunity.com/sharedfiles/filedetails/?id=574427407
http://steamcommunity.com/sharedfiles/filedetails/?id=574427347
http://steamcommunity.com/sharedfiles/filedetails/?id=574427469
http://steamcommunity.com/sharedfiles/filedetails/?id=574427563

**Comment by Kentersnoodlefactory** [comment]
I've also tested this multiple times this week, these c130's they really do behave in a way that a c130 should, no stupid tailstrikes which result in death and missery. They look nice both exteriorly and interior, much better than the current USAF IMO do. OH and you can actually land the bugger in speeds slower than 200km/h! There are a ton of diffrent version there is even the blue angels fat albert in there,

**Comment by Fourjays** [comment]
Accepted in the meeting on 13/12/15.

**Comment by Fourjays** [comment]
Added to the test modpack repository, changes awaiting deployment.
