### ISSUE TITLE
F-16C Fighting Falcon

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/blackwatchint#144]
**Description:**
- F-16C Fighting Falcon for USAF,ROKAF and other Country
- Various Weapon Equipment
- SEAD System(Currently working with Tigris for now.)
- ECM JAMMER for Self-Protection in SEAD Operation.
- Change the Loadout, Skin in Loadout Menu
- Custom Insignia Supported.
- Targeting system for Precision Strike.

**Download:** http://www.armaholic.com/page.php?id=27766
**Size:** 15MB

Posted as a result of #131 for consideration in replacing USAF pack.

**Comment by Fourjays** [comment]
The standalone F16C is of a high visual quality overall, with detailed exterior and interior. It has support for the loadout tent hangars with a configurable armaments and textures. The sounds are mostly pretty good, although the afterburner noise seems a little odd. It flies very nicely and feels much quicker than the USAF pack's F16C (it can actually achieve the speeds an F16 should be able to do). It also appears to feature some kind of special targeting system as well as a functioning ejector seat.

Have to be quite gentle on landings as it is easy to take medical damage.

Some screenshots:
http://steamcommunity.com/sharedfiles/filedetails/?id=574770949
http://steamcommunity.com/sharedfiles/filedetails/?id=574770711
http://steamcommunity.com/sharedfiles/filedetails/?id=574771043
http://steamcommunity.com/sharedfiles/filedetails/?id=574771129
http://steamcommunity.com/sharedfiles/filedetails/?id=574771188
http://steamcommunity.com/sharedfiles/filedetails/?id=574771339

**Comment by Kentersnoodlefactory** [comment]
It flies nice it looks nice, the ejector seat works fine, it can go faster than 500km/h which the current one we have can not.... It has a nice variety of weaponry which is nice, a few diffrent factions i.e Poland. It behaves more like the F16's i've tried in "hardcore" flight sims, which is nice.

Screenshots: http://imgur.com/a/n7iEy

**Comment by Fourjays** [comment]
Accepted in the meeting on 13/12/15.

**Comment by Fourjays** [comment]
Added to the test modpack repository, changes awaiting deployment.
