### ISSUE TITLE
Landing helicopters partially in water results in drowning

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/blackwatchint#147]
Landing a helicopter partially in water reportedly causes the occupants to go into an irreversible but non-deadly "downing" state. It also slowly damages the helicopter as if it was fully submerged. The drowning effects on the occupants can only be removed via death.

**Comment by Kentersnoodlefactory** [comment]
Aircraft seem to do the old arma thing and slowly take damage until fully destroyed if you are just partly in water. I would guess it is a arma bug which is non fixable.

**Comment by Fourjays** [comment]
Looks like a bug in vanilla Arma 3, so there isn't really anything we can do about it.

**Comment by Fourjays** [comment]
Closing as we can't fix this. Will reopen if something changes.
