### ISSUE TITLE
Replace ARP2 objects with fixed "lite" version

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/blackwatchint#153]
I have created a "lite" version of ARP objects to replace the existing version. This version is a tenth of the size (down from 80MB to 7MB), free of scripts that don't work and is no longer generated an "init player" message everytime somebody joins the server.

Initial testing looks good, but needs final checking on the server. Will be included in the modpack pending testing.

**Comment by TheGrandVizier** [comment]
Can has list of remaining objects for review?

**Comment by Fourjays** [comment]
Basically any that weren't broken and were possible to fit in a backpack:
- Laptop
- Toughbook
- Box of MREs
- Water Bottle
- Blackbox
- Smartphone
- Folder
- Passport
- MRE
- Cocaine
- Weed
- 8Ball
- Heroin
- Key
- Key Cards (5 colours)
- Paper
- Newspaper Stack
- Newspaper

Currently still limited to the Virtual Ammobox, but if I have time I'll try converting them to work with the Virtual Arsenal.

**Comment by Fourjays** [comment]
Confirmed working in multiplayer, but all of the objects appear on the ground rotated 90'.

**Comment by Fourjays** [comment]
Have split the bug off into its own issue (#161) and will proceed with including the custom configuration as-is.

Has been included in the test modpack repository and is ready for deployment.
