### ISSUE TITLE
Update the Nimitz Carrier configuration/positioning

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/blackwatchint#160]
As recently discussed, the Nimitz Aircraft Carrier setup on the template needs updating.
- The F22 (removed by #148) needs replacing with the F14.
- Aircraft positions may need adjusting to maximise the operational capabilities.

**Comment by Fourjays** [comment]
I will make a template to aid in copying the changes to all of the templates.

**Comment by ShiFoo** [comment]
corrections done with https://github.com/blackwatchint/blackwatchint/commit/03b55be806e84ba8c52d36906928055cc7502fb4 and https://github.com/blackwatchint/blackwatchint/commit/e94781aed2437a6b2a139af5414894bf1fc8a6ef. Closing
