### ISSUE TITLE
Update loadouts for cTab equipment

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/blackwatchint#163]
All loadouts need adjusting as follows for the new cTab:
- Platoon leader needs their own loadout.
- Platoon leader and platoon RTO/JTAC both need the "Rugged Tablet".
- Squad leader and squad RTO both need the "GD300 Android".
- Fireteam leader needs the "MicroDAGR" from "Terminals" (not to be confused with the ACE MicroDAGR or radio programming MicroDAGR).
- US 1985 loadout should not have any of the above included in it.
- The above items should be placed in the uniform/vest/backpack if possible.
- Ensure that no loadouts include the default GPS item.

**Comment by Fourjays** [comment]
Also need to include the "Helmet Cam" for the Squad and Fireteam leaders. Maybe a good idea to add to the Corpsmen and Engineer loadouts too.

**Comment by ShiFoo** [comment]
Committed to 121 with https://github.com/blackwatchint/blackwatchint/commit/8905fbedd8ee96b03cc71647e03470e9a98db641
