### ISSUE TITLE
Define group names for cTab

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/blackwatchint#170]
Group names should be defined in the templates so that our own platoon structure and group names will match those displayed in cTab.

**Comment by ShiFoo** [comment]
Group names will be assigned as soon as the leader of that group slots in. Currently reinforcement/new groups will still have the generic name. No idea how this can be fixed reasonably...

**Comment by ShiFoo** [comment]
Branches merged. Clsoing issue.
