### ISSUE TITLE
US Army OCP/UCP MMG Gunner Missing Backpack / Ammunition

### ISSUE THREAD

**Issue by CervenBWI** [blackwatchint/blackwatchint#172]

**Comment by CervenBWI** [comment]
As an FYI, this affects both the Armory, and the Pedestals.

**Comment by ShiFoo** [comment]
_unit addBackpack "usaf_ruck_mc";

its a USAF backpack.

**Comment by Fourjays** [comment]
That is probably a backpack from the USAF mod that we removed. All of the RHS stuff is prefixed with "rhsusf_" to my knowledge.

See here: http://class.rhsmods.org/rhsusaf/CfgVehicles.html
(I presume loadouts use the same class names that are defined in CfgWeapons, CfgVehicles, etc.)

**Comment by Fourjays** [comment]
Fixed by @wingatex in b4a334d4c06bea40e8db2b0aeb1c4e4a2bdc71c9.
