### ISSUE TITLE
Remove the Virtual Ammobox

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/blackwatchint#175]
With the BWI: Armory , Virtual Arsenal and ARP2 Objects now available via the arsenal, the Virtual Ammobox doesn't really serve much purpose anymore. We'd like to consider removing it in a future template update.

**Comment by ShiFoo** [comment]
Changes committed to feature branch 175-RemoveVAS.

**Comment by ShiFoo** [comment]
Changes merged from feature to develop branch. Closed
