### ISSUE TITLE
Remove pedestals from spawn locations

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/blackwatchint#176]
The addition of the BWI: Armory has made the pedestals at spawn obsolete. Once any minor issues with the Armory have been resolved we would like to remove the pedestals and associated objects from the spawn area.

**Comment by ShiFoo** [comment]
Will most likely not be done in a feature branch. Will be done directly on develop before branching.

**Comment by ShiFoo** [comment]
I would also like to delete the concrete walls... Should we keep at least one of the walls to line up on?

**Comment by ShiFoo** [comment]
Changes committed to develop. Closing.
