### ISSUE TITLE
Error messages in editor and on server

### ISSUE THREAD

**Issue by ShiFoo** [blackwatchint/blackwatchint#186]
I had different error messages popping up in the editor and while slotting in on the dedicated server:

http://steamcommunity.com/sharedfiles/filedetails/?id=579777790
http://steamcommunity.com/sharedfiles/filedetails/?id=579777849
http://steamcommunity.com/sharedfiles/filedetails/?id=579777744

**Comment by Fourjays** [comment]
First one is new though. Possibly a corrupt file on the server modpack.

Second and third ones are "normal" and are in mods that we can't really do much about (I've had them ever since the Q3 update).

**Comment by ShiFoo** [comment]
I was just on the server again playing sugar lake. The error did not occur again. And with the other 2 being "tolerable", we could close this issue.

**Comment by Fourjays** [comment]
Closing this issue. We'll reopen it if these issues occur again.
