### ISSUE TITLE
Merge squads and fireteams into one group

### ISSUE THREAD

**Issue by ShiFoo** [blackwatchint/blackwatchint#199]
All templates need to be adjusted so a whole squad will be in one "group".

**Comment by Fourjays** [comment]
I want us to be 100% certain on the configuration before taking action on this. Don't want changes made only to revert or alter them again a few days later.

**Comment by ShiFoo** [comment]
Agreed, and i want it to do with the pedestal removal. Its just that the action point existed. Details tbd

**Comment by ShiFoo** [comment]
Just to make sure: This would also eliminate the fireteams from the cTab devices, which i thought would be nice to have.
Just a side-effect of this change...

**Comment by Fourjays** [comment]
Eliminate them in what way? To my knowledge Fireteam's don't appear on the map, as the MicroDAGR they have is a receiver only.

**Comment by ShiFoo** [comment]
Oh, i mixed them up. No worries, my bad...

**Comment by wingatex** [comment]
RTO -> FTL -> CFR -> RIF1 -> RIF2

**Comment by ShiFoo** [comment]
Changes committed to develop. Closing.
