### ISSUE TITLE
Deployable medical tent

### ISSUE THREAD

**Issue by ShiFoo** [blackwatchint/blackwatchint#200]
The plan is to give ground troops the ability to deploy a medical tent. This should not be the decision of the Zeus anymore. The construction of the medical tent should be either bound to certain roles and/or require specific items.

Current idea: Platoon Logistics are the group that can construct and repackage the tent. A BAF static weapon "launcher" shall be duplicated and serve as a required item, next to the Toolbox.
The player having both items can build the tent. The "launcher" shall be consumed on use. Only the player with a toolbox can deconstruct the tent again. The "launcher" should be spawned on the position of the tent, which can be picked up again.

**Comment by ShiFoo** [comment]
sadly, i cannot open the UKBAF Weapons pack pbo for the desired launcher. It says that the file is corrupt even though it works ingame...

**Comment by Fourjays** [comment]
I had this problem before too. All of the 3CB mods are packed in a way that prevents them being unpacked.

If I understand correctly though, it should be possible to reference the model from another mod. Issue is finding the correct "path".

You could also check the full ARP objects mod again. Perhaps there is another item I could import to the arsenal for the purpose.

**Comment by ShiFoo** [comment]
I need some more information on how this should work. The launcher is currently hard to implement, because the only good item for it would be the launcher backpack for BAF static guns. This brings two problems: the BAF weapons pbo cannot be unpacked and when you "drop" the launcher it will actually render a tripod or the respective model. I am not really happy with this....
Some other questions would be:

- Should backpack items be required? (current implementation: MRE box and toolkit)
- Should a certain vehicle type nearby be required? (e.g. tent can only be constructed if a HEMMT is <20m next to you)
- if items required: Should the required items stay as the MRE box and the toolkit (for now)?
- Should the ability to build the tent be bound to a certain profession? ( e.g. only the engineer with the ACE variable set correctly )

**Comment by ShiFoo** [comment]
To be discussed: With the engineer being vital for the corpsman it is foreseeable that the engineer will become the new "medical driver". If this happens, the logistics drivers become obsolete. We need to reconsider if this is the design we want and if the consequences are acceptable.

**Comment by ShiFoo** [comment]
Enhancements merged to develop. Closing.
