### ISSUE TITLE
New medical / logistics platoon structure

### ISSUE THREAD

**Issue by ShiFoo** [blackwatchint/blackwatchint#229]
The structure of medical and logistics is subject to change.

Group 1: Platoon Leader + JTAC (PRTO)
Group 2: Assistant Platoon Leader (PL loadout) + 2x Corpsmen + 2x Engineer

The driver roles shall disappear. I will make the change on the Template.vr. When its done, this change must be ported into every map:

https://github.com/blackwatchint/blackwatchint/wiki/Making-all-players-playable-in-a-template-with-Notepad

Make sure that that everything is in the correct order. Changes are to be committed on "develop" branch.

__@ShiFoo:__
- Template
- Al-Jak
- Altis
- Bozcaada
- Bukovina
- Bytsrica
- Chernarus
- Chernarus Winter
- Chernarus Summer
- FATA
- Gorgona

__@wingatex:__
- Imrali
- Isla Duala
- Isla Panthera
- Kunduz
- Lingor
- Lost Island
- Lost Island Winter
- Nziwasogo
- Porto
- Rahmadi
- Sahrani

__@abelarno :__
- Shapur
- Southern Sahrani
- Stratis
- Sugar Lake
- Takistan
- Takistan Mountains
- United Sahrani
- Valtatie5
- Vietnam
- Wake Island
- Zargabad

**Comment by ShiFoo** [comment]
Template + Al-Jak up to Gorgona done and committed to develop.

**Comment by abelarno** [comment]
Shapur to Zargabad done and committed to develop.

**Comment by ShiFoo** [comment]
@abelarno i just had a look at the Shapur template. Sadly the unit names are almost all wrong. Seems like you merged the template before deleting the old player objects. When ArmA detects the same object name, it appends a "_1".

Example:
blufor platoon leader:b_pl1_ple_pl
your template has: text="b_pl1_ple_pl_1"

You can use notepad++ to search and replace this but be careful about the HC_1.

**Comment by abelarno** [comment]
Aah, missed that one then, gonna fix it asap.

2016-01-15 8:48 GMT+01:00 ShiFoo <notifications@github.com>:

**Comment by ShiFoo** [comment]
All changes done. Closing.
