### ISSUE TITLE
New Faction - CSAT

### ISSUE THREAD

**Issue by blackwatchint** [blackwatchint/blackwatchint#23]
New Faction for our Loadout stands.

- Squad Leader
- Fireteam Leader
- Radio Transmitter Operator
- Corpsman
- Engineer
- Combat First Responder
- Automatic Rifleman
- Assistant Automatic Rifleman
- Rifleman (AT)
- Heavy Machine Gun (NSV Tripod)
- Helicopter Pilot
- Designated Marksman 
- Sniper
- Demolition Man
- Crewman
- Rifleman

**Comment by ShiFoo** [comment]
Proposal for CSAT (1:1 copy, just uniform, vest, backpack and main gun)
If agreed on, role-specific loadout can be created:

Khaki:
>removeAllWeapons player;
>removeAllItems player;
>removeAllAssignedItems player;
>removeUniform player;
>removeVest player;
>removeBackpack player;
>removeHeadgear player;
>removeGoggles player;
>
>comment "Add containers";
>player forceAddUniform "U_O_CombatUniform_ocamo";
>for "_i" from 1 to 3 do {player addItemToUniform "30Rnd_556x45_Stanag";};
>player addVest "V_HarnessO_brn";
>player addBackpack "B_Carryall_khk";
>player addHeadgear "H_HelmetLeaderO_ocamo";
>
>comment "Add weapons";
>player addWeapon "arifle_TRG21_F";

Urban:
>removeAllWeapons player;
>removeAllItems player;
>removeAllAssignedItems player;
>removeUniform player;
>removeVest player;
>removeBackpack player;
>removeHeadgear player;
>removeGoggles player;
>
>comment "Add containers";
>player forceAddUniform "U_O_CombatUniform_oucamo";
>for "_i" from 1 to 3 do {player addItemToUniform "30Rnd_556x45_Stanag";};
>player addVest "V_HarnessO_gry";
>player addBackpack "B_Carryall_oucamo";
>player addHeadgear "H_HelmetLeaderO_oucamo";
>
>comment "Add weapons";
>player addWeapon "arifle_TRG21_F";

**Comment by adios113** [comment]
Good job, but it has to be role specific cause of the extra gear regulations like optics, 40mm and so on

**Comment by ShiFoo** [comment]
I just wanted to have an agreement of basic appearance first. Otherwise, maybe not even me, puts time and work into the loadout and someone says that it should look differently

**Comment by adios113** [comment]
http://blackwatch-int.com/field-manual/gear-regulations

**Comment by Fourjays** [comment]
Rejected in the meeting on 06/12/2015.
