### ISSUE TITLE
Investigate Virtual Arsenal whitelisting

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/blackwatchint#234]
We want to investigate the possibility of adding a whitelist to the Virtual Arsenal box, limiting the available gear as desired.

**Comment by abelarno** [comment]
I've done this before. It's a pretty simple process that just takes a lot of time to do, especially with the amount of weapons/items/uniforms that we use. As far as I know there is no blacklisting option.

This is the script we used:
https://gist.github.com/abelarno/da6e5f7d9ecc0f86e309

**Comment by ShiFoo** [comment]
If this is local to the player we could think about i.e. enabling zoomed scopes to the leadership positions only.

**Comment by Fourjays** [comment]
Action item created with #263 for next milestone.
