### ISSUE TITLE
Imrali spawn point

### ISSUE THREAD

**Issue by wingatex** [blackwatchint/blackwatchint#238]
Imrali spawn point needs to move to free up map for more play ability.

**Comment by ShiFoo** [comment]
Could you please elaborate what is wrong with the current one?

**Comment by TheGrandVizier** [comment]
This is posted at my request as Zeus.

The current point is too close to actual objectives. An acog scope'd guy can shoot from the radio tower hill into the player spawn zone.
Also, it removes the entire lighthouse area from the game.

I far prefer the previous the previous spawnpoint at the south (not the one that was borked on a hillside, but just south, next to where some buildings are).

At it stands, the southern part of the map is the useless one that should be sacrificed.
Lighthouse sector very useful as objective / secondary objective.

**Comment by ShiFoo** [comment]
Ok, sounds reasonable.

**Comment by ShiFoo** [comment]
Change done. Closing.
