### ISSUE TITLE
New Faction - NATO (A3 Vanilla)

### ISSUE THREAD

**Issue by blackwatchint** [blackwatchint/blackwatchint#24]
New Faction for our Loadout stands.

- Squad Leader
- Fireteam Leader
- Radio Transmitter Operator
- Corpsman
- Engineer
- Combat First Responder
- Automatic Rifleman
- Assistant Automatic Rifleman
- Rifleman (AT)
- Heavy Machine Gun (NSV Tripod)
- Helicopter Pilot
- Designated Marksman 
- Sniper
- Demolition Man
- Crewman
- Rifleman

**Comment by ShiFoo** [comment]
Proposal for NATO Soldier ( 1:1 copy, only uniform, vest and backpack )

>removeAllWeapons player;
>removeAllItems player;
>removeAllAssignedItems player;
>removeUniform player;
>removeVest player;
>removeBackpack player;
>removeHeadgear player;
>removeGoggles player;
>
>player forceAddUniform "U_B_CombatUniform_mcam";
>player addVest "V_PlateCarrier1_rgr";
>for "_i" from 1 to 2 do {player addItemToVest "16Rnd_9x21_Mag";};
>player addBackpack "UK3CB_BAF_B_Bergen_MTP_Rifleman_L_A";
>
>player addHeadgear "H_HelmetB";
>
>player addWeapon "arifle_MX_ACO_pointer_F";
>player addPrimaryWeaponItem "acc_pointer_IR";
>player addPrimaryWeaponItem "optic_Aco";
>player addWeapon "hgun_P07_F";

**Comment by Fourjays** [comment]
Rejected in the meeting on 06/12/2015.
