### ISSUE TITLE
PMC Platoon Leader missing backpack radio

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/blackwatchint#242]
As title, the PMC loadout for Platoon Leader does not have a backpack radio.

**Comment by ShiFoo** [comment]
I dont know what happend but it seems that the templates on the server are not the most up-to-date ones. The master branch ( which should represents the current state on the server ) has the black LR radio backpack:

_unit addBackpack "tf_rt1523g_black";

I also confirmed it locally on my machine... Either way: it is fixed. Closing.
