### ISSUE TITLE
PMC Corpsman missing Surgical Kit

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/blackwatchint#244]
The PMC loadout for Corpsmen seems to be missing the Surgical Kit.

**Comment by Fourjays** [comment]
Also appear to be missing morphine and epinephrine injectors. Will investigate further.

**Comment by Fourjays** [comment]
Missing morphine/epinephrine must have been caused by something else as they appear when I checked again.

Surgical kit still missing though.

**Comment by ShiFoo** [comment]
The backpack is too small for all the medical gear. I changed it to a Carryall some days ago but Nik mentioned the Kitbag to be a good alternative.

**Comment by TheGrandVizier** [comment]
Tested, confirmed, this is the only bluefor corpsmen loadout that has this size of bag.

**Comment by ShiFoo** [comment]
Will be fixed in the next milestone. Closing.
