### ISSUE TITLE
New Faction - PMC

### ISSUE THREAD

**Issue by blackwatchint** [blackwatchint/blackwatchint#25]
New Faction for our Loadout stands.

- Squad Leader
- Fireteam Leader
- Radio Transmitter Operator
- Corpsman
- Engineer
- Combat First Responder
- Automatic Rifleman
- Assistant Automatic Rifleman
- Rifleman (AT)
- Heavy Machine Gun (NSV Tripod)
- Helicopter Pilot
- Designated Marksman 
- Sniper
- Demolition Man
- Crewman
- Rifleman

**Comment by ShiFoo** [comment]
Proposal for PMC Soldier ( only uniform, vest, backpack and main rifle)

>removeAllWeapons this;
>removeAllItems this;
>removeAllAssignedItems this;
>removeUniform this;
>removeVest this;
>removeBackpack this;
>removeHeadgear this;
>removeGoggles this;
>
>comment "Add containers";
<this forceAddUniform "U_I_G_Story_Protagonist_F";
>this addVest "V_PlateCarrier1_PMC_blk";
>this addBackpack "PMC_AssaultPack_Blk";
>this addHeadgear "usaf_capb_headphones_blk";
>
>comment "Add weapons";
>this addWeapon "arifle_Mk20_F";
>this addPrimaryWeaponItem "RH_SFM952V";
>this addPrimaryWeaponItem "RH_compm4s";
>this addWeapon "RH_m9";
>this addHandgunItem "RH_m9qd";
>this addHandgunItem "RH_M6X";
>this addWeapon "Binocular";

**Comment by ShiFoo** [comment]
PMC loadout finished and merged to develop
