### ISSUE TITLE
ALiVE Object moving system.

### ISSUE THREAD

**Issue by adios113** [blackwatchint/blackwatchint#250]
So, here is another ALiVE feature I discovered, that allows us to move, lift, load objects and even tow vehicles. It requires only two Modules to be placed inside the template - "Alive (Required)" and "Player Combat Logistics". Objects can be whitelisted and it is really easy to use - trough action menu. 
More detailed documentation: http://alivemod.com/wiki/index.php/Logistics_Support
This will solve #221. Works with objects spawned trough Zeus. It is safe to add those two modules to our templates. You will have an occasion to see how it works on Saturday.

**Comment by Fourjays** [comment]
Not a regular template issue or workaround for a bug. It is potentially a cool feature available through ALiVE which we now have available (#247), but if you think it impacts #221 please post in there, thanks.
