### ISSUE TITLE
New Faction - Russian EMR

### ISSUE THREAD

**Issue by blackwatchint** [blackwatchint/blackwatchint#26]
New Faction for our Loadout stands.

- Squad Leader
- Fireteam Leader
- Radio Transmitter Operator
- Corpsman
- Engineer
- Combat First Responder
- Automatic Rifleman
- Assistant Automatic Rifleman
- Rifleman (AT)
- Heavy Machine Gun
- Helicopter Pilot
- Designated Marksman 
- Sniper
- Demolition Man
- Crewman
- Rifleman

**Comment by ShiFoo** [comment]
New faction committed to feature branch.

**Comment by ShiFoo** [comment]
Branches merged. Closing.
