### ISSUE TITLE
Client + Server Crash when Remote Controlling a spawned unit

### ISSUE THREAD

**Issue by TheGrandVizier** [blackwatchint/blackwatchint#261]
Reproduce:
1. Load up any map.
2. Spawn US Army Grenadier (or a team containing one)
3. RC the grenadier

Results:
Grenadier Spawns with invisible gun.
On RC:
Client Crashes
Server Crashes

**Comment by LordCavac** [comment]
Just tried this in SP following those exact steps and there is no issue, I'll test on MP with no HC next.

**Comment by TheGrandVizier** [comment]
Verdicts:
US Army, *NOT USMC* Grenadier spawns with a bugged (invisible) gun.
RCing him will crash the server and the client.

The information in the original post has been revised.

**Comment by LordCavac** [comment]
Tried loading in as grenadier in SP using mission editor, client crashed immediately without even loading.

**Comment by Fourjays** [comment]
Managed to track down the cause of the crash, which is caused by ASR AI 3's RHS config file.

**Comment by abelarno** [comment]
The config file is over a year old (created januari 10 2015). With updates to RHS it probably has compatibility issues. I recommend to remove it for now while we try to fix it.

**Comment by Fourjays** [comment]
Created action item for its removal (#265).
