### ISSUE TITLE
Deployable FOB

### ISSUE THREAD

**Issue by ShiFoo** [blackwatchint/blackwatchint#262]
Like title says: New FOB to be implemented analogue to the medical tent.

**Comment by ShiFoo** [comment]
First draft committed to feature branch. Flagpole added to all maps, engineers devided in FOB carrier and tent carrier. Code cleanup for loadouts: eliminated first parameter for loadout scripts ( it was a technical neccessity for the pedestals ) and added parametrization ( 2 manifestations of an engineer ).

Pending: APL/PL notification / query for waiting reinforcements at the respawn

**Comment by Fourjays** [comment]
Some changes need to be made to the FOB, based on recent discussions:
 - There should be no FOB to Medical Tent requirement, to ensure op styles aren't restricted.
 - There should be no option to enable the BWI Armory.

Also some questions surrounding the planned ammo resupply:
 - Is the contents of the supply persistent between deployments of the FOB?
 - How does it handle the variation in ammo types between factions, roles and loadouts?

**Comment by ShiFoo** [comment]
> -There should be no FOB to Medical Tent requirement, to ensure op styles aren't restricted.
> -There should be no option to enable the BWI Armory.
Changes committed to feature branch:

> -Is the contents of the supply persistent between deployments of the FOB?
Yes

> -How does it handle the variation in ammo types between factions, roles and loadouts?
My idea was to make it side-dependent. If we play blufor, the box would contain all possible ammo types for blufor which is mainly stanag 5.56, G36 ammo, LMG, MMG, marksman ammo in moderate amounts. Opfor and Independent side are implemented the same way.

**Comment by ShiFoo** [comment]
changes merged back to develop. Closing.
