### ISSUE TITLE
Add FOB item to modpack

### ISSUE THREAD

**Issue by ShiFoo** [blackwatchint/blackwatchint#264]
The new BWI_Support mod needs to be added to the repo containing the medical tent and FOB.

**Comment by ShiFoo** [comment]
New pbo has been uploaded to Test Repo FTP directory.
- Deleted BWI_medical_tentBox.pbo
- Added BWI_Support.pbo (includes tent box and fob box)

Please set up the test server instance accordingly.

**Comment by Fourjays** [comment]
Added to the test repository, awaiting deployment.
