### ISSUE TITLE
Remove ASR AI RHS configuration

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/blackwatchint#265]
As per #261, the ASR AI RHS configuration file is causing client and server crashes in specific situations. Will need removing.

**Comment by TheGrandVizier** [comment]
What are the implications of this?
Does it mean no faction will now be under ASR influence?

**Comment by ShiFoo** [comment]
No, it will be that RHS AI will only be all "on one skill level". The RHS config, for example, altered the spotting and aiming value of an AI unit if it has a magnified scope.
With the removal of the config, all AI will be on "insurgent" level which is a fair average of all the ASR AI skill levels.

**Comment by Fourjays** [comment]
Removed in the test repository, changes awaiting deployment.
