### ISSUE TITLE
New Faction - UN

### ISSUE THREAD

**Issue by blackwatchint** [blackwatchint/blackwatchint#27]
New Faction for our Loadout stands.

- Squad Leader
- Fireteam Leader
- Radio Transmitter Operator
- Corpsman
- Engineer
- Combat First Responder
- Automatic Rifleman
- Assistant Automatic Rifleman
- Rifleman (AT)
- Heavy Machine Gun
- Helicopter Pilot
- Designated Marksman 
- Sniper
- Demolition Man
- Crewman
- Rifleman

**Comment by ShiFoo** [comment]
I am interested in what "base faction" the UN should have. Its just an existing faction with blue helmet/vest. The predefined UN troops look like these:

http://images.akamai.steamusercontent.com/ugc/367406736565032417/ED5996368A6BC78D823264DDF71857E4A5438C35/

**Comment by ShiFoo** [comment]
Last info on this was to implement UN with Bundeswehr as base faction. Is this still valid or should it be something completely else? (like the screenshot, having not state-of-the-art equipment + AKs?)

**Comment by Fourjays** [comment]
As discussed in the meeting on 03/01/2016, UN loadouts will use Bundeswehr as the base faction.

**Comment by ShiFoo** [comment]
Feature branch merged. Closing.
