### ISSUE TITLE
Add Zeus specific loadout

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/blackwatchint#276]
We want to add a loadout for Zeuses that makes them more easily identifiable at spawn. The loadout can be civilian, press or can remain military based.

The loadout should contain a long range radio and not include a cTab device (so they don't appear on the device).

**Comment by abelarno** [comment]
They should have a sweet-ass big white beard.

**Comment by TheGrandVizier** [comment]
My suggestion is a como or black uniform, aviators, beret.
Probably can be unarmed.

**Comment by ShiFoo** [comment]
This will need its own loadout file, an appropriate entry in the armory and changes in the init line of zeus objects in the mission.sqm

**Comment by ShiFoo** [comment]
Changes committed to develop. Closing.
