### ISSUE TITLE
Ammoboxes for Russian Medium AT are empty

### ISSUE THREAD

**Issue by TheGrandVizier** [blackwatchint/blackwatchint#279]
as title says, Russian medium AT boxes spawn empty, and so do their ammo boxes.

The russian medium AT loadout has no medium AT.

They are the same issue, as i gather that jays used the AT referenced in loadouts.

**Comment by Fourjays** [comment]
There is no Medium AT launcher available as a supply box, only ammo. It does use the same class names as the loadouts do.

According to the RHS documentation, the class names we have in the loadouts and ammoboxes are correct:
```
rhs_weap_rpg7
rhs_rpg7_PG7VL_mag
```

**Comment by Fourjays** [comment]
Obtaining the item via an Arsenal and exporting the loadout also produces the same classname.

This is similar to my issues with the HLC .300 ammo, which also has all the correct classnames (verified by the configs) and won't load.

**Comment by Fourjays** [comment]
Checked the RHS configs and verified all classnames are correct and match documentation.

**Comment by Fourjays** [comment]
@TheGrandVizier does the loadout have the weapon, or is it missing that too?

**Comment by ShiFoo** [comment]
I have checked all three camos: They have the launcher and the rockets... without seeing it live, i cannot spot the error... Can you remember which camo it was EMR/FLORA/MFLORA?

**Comment by TheGrandVizier** [comment]
M. FLORA

**Comment by ShiFoo** [comment]
_unit addWeapon "rhs_weap_rpg7";
_unit addSecondaryWeaponItem "rhs_acc_pgo7v";
for "_i" from 1 to 2 do {_unit addItemToBackpack "rhs_rpg7_PG7VL_mag";};

@TheGrandVizier - Has this been reported to you are did you experience it yourself? Could be a problem with the armory and not with the loadout itself. Going to investigate later.

**Comment by TheGrandVizier** [comment]
It was reported to me that the loadouts are broken.
As a workaround I attempted to spawn the relevant ammoboxes made by jays.
The boxes were empty.

**Comment by TheGrandVizier** [comment]
@Fourjays

**Comment by Fourjays** [comment]
This is two issues independent of one another. Split the Armory issue off to #280.

**Comment by Fourjays** [comment]
The ammoboxes for Russian MAT spawn empty and do not contain the 4 RPG rounds that should be there. None of the RPG rounds appear in the ammobox customization list, and the only way to obtain them is by adding an RPG-7V2 to the box and checking the inventory.

This appears to be a bug or limitation of RHS, so I have contacted them to verify it isn't an error on our end before filing a bug report.

In the meantime I will configure the box to spawn the RPGs themselves.

**Comment by Fourjays** [comment]
Got confirmation from RHS that this will be fixed in an upcoming release.

**Comment by Fourjays** [comment]
Updated the Medium AT box to include the launchers which come with 2x rounds each. Change has been deployed to the test repository, awaiting deployment.

Created #285 to reverse this workaround at a later point.
