### ISSUE TITLE
Additional Loadouts for existing factions

### ISSUE THREAD

**Issue by blackwatchint** [blackwatchint/blackwatchint#28]
- Heavy Machine Gun
- Helicopter Pilot
- Jet Pilot
- Designated Marksman 
- Sniper
- Demolition Man
- Crewman

USMC, US Army, UK, Bundeswehr, Russia - All loadouts variants (wood, desert)

**Comment by adios113** [comment]
Moved to the  23NOV2015 Milestone. Added to the meeting agenda.

**Comment by adios113** [comment]
Heavy Machine Gun - Making a HMG Team. (Tripod, Weapon Backpacks, 3rd guy ammo/spotter/additional gear)

Helicopter - Backpack Radio gone, SMG, Flares, Demoblock, 3mags; pistol 3mags;

Jet Pilot - Parachute as a backpack, pistol only, limited supply gear.

Designated Marksman - 7.62mm 20rnd, rangefinder, no gps and things, part of a fireteam element

Sniper - Ghuil Suit, .50 cal sniper, basicaly, programmable radio, range card.

Demoman - Part of a fireteam, standard fireteam + explosives

Crewman - Crewman uniform helmet, programmable radio, gps, carbine assault rifle

Engineer - add a mine detector.

**Comment by TheGrandVizier** [comment]
Just to be sure - is Sniper / Sniper Team getting GPS?
I'd think on one hand, they are sorta hi tech so why not. On the other, a sniper should make do without one, in terms of navigation skills.

**Comment by ShiFoo** [comment]
This is a huge task, also for other factions. And also very time consuming. Maybe we can open this up for the others. Let people send in loadout suggestions (in what way and to what extent would be a question). We could speed up the process and people will have an impact on the templates. Maybe they even have something already... Thoughts?

**Comment by adios113** [comment]
The thing is, that we will have to redo them ourselves. I tried that and i had to fix stuff like gear regulations, magazines count. It will be quicker if we do it ourselves, thats why we are here.

**Comment by ShiFoo** [comment]
Added new Russian loadouts from #54 to pedestals in commit https://github.com/blackwatchint/blackwatchint/commit/72d22140642eba2fae2cb8dc2bad130db88bdf1e

**Comment by Fourjays** [comment]
If there's a template on the server for #54, #55 and #56 available for testing, I'll get the testers to go through all the new loadouts over the weekend.

**Comment by ShiFoo** [comment]
#56 is still TODO. I am currently working on it. If all goes to my personal plan, we can have a template tomorrow.

**Comment by ShiFoo** [comment]
Ok, i quickly plowed through the USArmy and UK loadouts. Template on the server: "Virtual Reality" - "[BWI]Template_v2.1.vr"

**Comment by ShiFoo** [comment]
All loadouts done. Closed
