### ISSUE TITLE
Russian MAT loadouts do not load from Armory

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/blackwatchint#280]
The Russian MAT loadouts in the Armory do not load, producing an error as pictured below:
http://steamcommunity.com/sharedfiles/filedetails/?id=619958778

Appears they are trying to load from a HAT file, which do not exist. Additionally, entries for HAT appear despite there being no Russian HAT loadouts available.

**Comment by ShiFoo** [comment]
Already spotted the error. It is an index problem inside the armory. Easy to fix.

**Comment by ShiFoo** [comment]
Fix merged to release and master branch. Closing.
