### ISSUE TITLE
Enemies actively target unconcious individuals

### ISSUE THREAD

**Issue by TheGrandVizier** [blackwatchint/blackwatchint#284]
According to ACE documentation and public statements, this should not happen.
I don't want to speculate, but this should not happen as much as it is happening.
It's one thing when an unconscious person is fatally hit while being carried or laying unconscious next to a conscious player.
This hasn't been the situation, to my understanding and personal experience.
Something is rotten in the kingdom of Denmark.-

**Comment by Fourjays** [comment]
I remember reading a discussion about them tweaking it so they engage unconcious inidividuals, because they were just ignoring unconcious players entirely. Not sure when or if it was implemented. Trying to find the discussion.

**Comment by Fourjays** [comment]
The AI do not currently engage unconcious individuals. See the discussion at acemod/ACE3#3121 where people are asking for them to do so.

**Comment by TheGrandVizier** [comment]
The situation as it was last night, we were positioned in a line formation, on a hilltop.
The closest person to either side of me were spaced at least 2 meters out on either side.
Between falling unconscious and dying i took at least 4 single shot bullets (judging by sound + redness effect)

**Comment by Fourjays** [comment]
At 2 meters it could just be the AI suppressing your position in general or firing at targets nearby and missing. The AI is pretty inaccurate now and suppress a lot. The only other possibility is ASR considers unconscious players to still be alive.

**Comment by ShiFoo** [comment]
Downed player are switching faction to civilian (purple icon) as seen in Zeus. If the AI faction is not actively set hostile towards civilians, AI should not shoot it on purpose. This is not editable through the editor. You have to force it via the setFriend command

west setFriend [civilian, 0];

**Comment by TheGrandVizier** [comment]
Can close, i am obviously just paranoid.

**Comment by Fourjays** [comment]
Closing as @TheGrandVizier is paranoid.
