### ISSUE TITLE
FOB can't be placed by FSA

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/blackwatchint#319]
The FOB can't be placed by FSA engineers, instead displaying a script error as pictured in the following screenshot: http://images.akamai.steamusercontent.com/ugc/320123842415345621/3EB632630D1D6B7E5CFB4572BDE7044B0482AE1A/

**Comment by ShiFoo** [comment]
Already spotted the error. I will test it when i get home today.

**Comment by ShiFoo** [comment]
Changes committed to develop. Closing.
