### ISSUE TITLE
Arsenal: Double Uniform entries.

### ISSUE THREAD

**Issue by TheGrandVizier** [blackwatchint/blackwatchint#33]
There are quite a few uniforms that show up in the arsenal, most times consecutively.
The various officer uniforms are a good example.
Captain, Second LT, and other officer designations and ranks.

**Comment by adios113** [comment]
Yea, those are from USAF modpack and from what i saw, these are different color variants.
Make sure that those are exactly the same uniforms.

**Comment by wingatex** [comment]
a lot of mil uniforms are same but patches change
listed below are uniforms what are duplicates
Counter sniper - duplicate
doctor cloths / fatigues - duplicate but hand changes position
Firetean member - both sets duplicate (4 total)
hevey weapons member - duplicate 
heli pilot flight suit RAF / RN - same but diffrent name
all "officer" unifors - duplicated
Pilot green / tan - duplicate
pilot coveralls nato - duplicate
Platoon commander - 2 sets duplicate
squad commander - 2 sets duplicate
squad leader - 2 sets duplicate
Policeman civ fatigues / clothes - duplicate but hand changes position
Team Leader - 2 sets duplicate

**Comment by TheGrandVizier** [comment]
Do these entities have a unique identifier of some type under the hood?
Perhaps we can surgically remove the dupes?

**Comment by blackwatchint** [comment]
@adios113 are we able to remove or disable the duplicate items?

**Comment by Fourjays** [comment]
@adios113 Are we able to remove or disable the duplicates?

**Comment by adios113** [comment]
Nope, without messing with the mod.

**Comment by TheGrandVizier** [comment]
Can you be more specific please?
What prevents us from unpacking this fucker and removing what we want?

**Comment by adios113** [comment]
We don't have the knowledge neccessary to edit/create mods like that. We have no mod makers in the team. I can create a basic mod, but I cannot do anything more complicated.

**Comment by Fourjays** [comment]
@ShiFoo Do you know of any way to remove or disable these duplicate arsenal entries?

**Comment by wingatex** [comment]
I think it is a mod doing this so it should be as simple as going into the mod and editing out the duplicates?

**Comment by ShiFoo** [comment]
I currently can't tell if it is possible or not. Usually mods have central files that the Arma 3 Engine can read to process the mod's contents. Be advised though: We also have #71 . We need to make sure we know what we are doing. The keys are explicitly designed to rule out that somebody has changed the mod. Altering the mods content will make the key verification fail and we might have to sign the mods again with our own private key. In my opinion, we need more time to familiarize ourselves with the options we have to get rid of duplicate entries. Even without the use of keys, we have no idea what we are doing.
Duplicate entries are not really disrupting gameplay and the effort for getting rid of them seems greater than the benefit. We can do it, but it needs more time.

**Comment by TheGrandVizier** [comment]
My logic, ifu, is that while it is insignificant here, it could be a very
useful ability for us to have.

Totally agree on priority.

**Comment by wingatex** [comment]
making our own keys inst that hard, i have done it myself before for a fix to the smoke grenades.

**Comment by ShiFoo** [comment]
Yeah making the private key and signing the pbo's is no big deal. But was the server configured to actually use the key? Because i would bet that no client would have been able to connect!
@TheGrandVizier After we have processed entries from the issue list, ( at least ) aDi and i will look into mods.

**Comment by wingatex** [comment]
yes i did i created my own key and server key for the file

**Comment by Fourjays** [comment]
Guys please make sure we keep the discussion focused on what options are available for solving the issue. @wingatex has created working bisigns and server keys before when we had them enabled on the server.

This will go on the backlog for now.

**Comment by Fourjays** [comment]
@wingatex and myself narrowed this down to the USAF mod last night, specifically the USAF_SFS.pbo file. I've reported the issue at fullerpj/united-states-air-force-mod#73 and hopefully we'll see a fix in the next update of the USAF mod.

**Comment by Fourjays** [comment]
This issue has been resolved by #148.
