### ISSUE TITLE
Bozcaada Turkish Island

### ISSUE THREAD

**Issue by blackwatchint** [blackwatchint/blackwatchint#41]
**Description:** Bozcaada is an island of Turkey in the northeastern part of the Aegean Sea. Administratively, the island constitutes the Bozcaada district of Çanakkale province. With an area of 39.9 km² it is the third largest Turkish island after Imbros and Marmara. In 2011, the district had a population of 2,472. The main industries are tourism, wine production and fishing. The island has been famous for its grapes, wines and red poppies for centuries.

**Download:** http://www.armaholic.com/page.php?id=29580
**Size:** 140MB

**Comment by ShiFoo** [comment]
I have played Bozcaada in some Battle Royale matches. It has one uniqueness to it which is already visible in the editor:
http://steamcommunity.com/sharedfiles/filedetails/?id=548713411

Contrary to what i have written on the forums, Bozcaada isn't like Altis at all. It has incredible grade of detail and lots of different places and settings to explore:
http://steamcommunity.com/sharedfiles/filedetails/?id=548713447
http://steamcommunity.com/sharedfiles/filedetails/?id=548713519
http://steamcommunity.com/sharedfiles/filedetails/?id=548713547
http://steamcommunity.com/sharedfiles/filedetails/?id=548713571

From arid and deserted landscapes to forest-like areas with beautiful vegetation 
http://steamcommunity.com/sharedfiles/filedetails/?id=548713651
http://steamcommunity.com/sharedfiles/filedetails/?id=548713623

It succeeds in combining the spectrum of mediterranean landscapes with nice visual details.
From what i can say performance-wise. Playing Battle Royale with 60 people is no issue at all.

In my opinion Bozcaada would be valuable addition to our map pool!

**Comment by Kentersnoodlefactory** [comment]
I tested this map, I'm on the same page as IFu to some extent. It's very detailed. With lots of small details and a good looking map design in general, it has great fps. Which can obviously be explained by the rather small size of the map.

I think it could be a nice addition to the map pool, it could certainly be used for some more stealthy low profiled missions. But it is very open and doesn't have many houses villages, some parts of the map is more or less empty whilst the places which a occupied are of extremely high detail. This map would fit for a rescue the POW style type of mission, dark spec-op and stuff like that. Not for the larger operations with vehicles, it is simply just to open for that. It would not work to move from one town to another with enemy vehicles as from most angles they would spot you from a far distance, and ofc same if you are in a vehicle heading for AO.

**Comment by DawkTux** [comment]
So i've looked at this map for about an hour and a half and i have to agree with both ifus and Kenters statement about the performance, overall it seems extremly good compared to most other maps which i guess can be explained by the lack of larger cities and the overall smaller scale of the map. It has some neat little military bases and the open center of the map would would be perfect for long range tank battles in my opinion. The main city in the north east, looks nice for urban combat as well, with its narrow streets. 

What i don't like is the fact that this map looks the way it does, yes it is an overall nice map but the fact that we have Imrali in the pack which is used extremly rarely speaks for itsself imo. What i miss the most with this map is that one unique thing, the thing that separates it from all the other maps.


If we really want to add more maps then we should make sure that we use them, the last thing we really need is another map that nobody uses. 

Something that should also be considered - especially when thinking about adding maps is asking the regular Zeuses about their opinion. It is all nice and well if we performance test those maps and if we like them but it is the Zeuses that make the missions on them.

**Comment by Fourjays** [comment]
This map has a very rural feel to it with wide open farmland and hills. It isn't a huge map, but at the same time doesn't feel small. There are numerous points of interest throughout the map, such as woodland areas, a nicely made airport and farm houses.

The performance of this map looks good and there's no obvious issues with it. It uses Arma 3 assets throughout so many buildings are enterable and the overall quality looks on a level with Bohemia's own maps. As nice as the open terrain is I'm concerned about how practical it is for the ops.

http://steamcommunity.com/sharedfiles/filedetails/?id=565045219
http://steamcommunity.com/sharedfiles/filedetails/?id=565045301
http://steamcommunity.com/sharedfiles/filedetails/?id=565045393
http://steamcommunity.com/sharedfiles/filedetails/?id=565045562
http://steamcommunity.com/sharedfiles/filedetails/?id=565045628
http://steamcommunity.com/sharedfiles/filedetails/?id=565045835
http://steamcommunity.com/sharedfiles/filedetails/?id=565045903
http://steamcommunity.com/sharedfiles/filedetails/?id=565045963

**Comment by Fourjays** [comment]
Accepted into the modpack during meeting on 29/11/15.

**Comment by TheGrandVizier** [comment]
Uploaded to repo.

**Comment by Fourjays** [comment]
Built into the test repository, tested and pushed to live.
