### ISSUE TITLE
Santa Catalina

### ISSUE THREAD

**Issue by blackwatchint** [blackwatchint/blackwatchint#42]
**Description:**
Santa Catalina Island for Arma 3 is an accurate replication of the real world Island located just off the coast of Southern California, USA. The island's only town, Avalon, features traditional American homes and a lovely downtown; made with over 30 unique buildings, objects and textures. Away from the town, you'll find Catalina's chaparral biome makes for interesting and intense battles in it's hilly terrain and dense vegetation. 

**Download:** http://www.armaholic.com/page.php?id=29035
**Size:** 165MB

**Comment by ShiFoo** [comment]
I think Santa Catalina is a small beautiful island. Colouring is quite nice. Arid ground with green bushes and trees.

http://steamcommunity.com/sharedfiles/filedetails/?id=548705778

Looks a bit like Stratis' little brother. Terrain is very hilly.
Main focus has the small town on the shore:
http://steamcommunity.com/sharedfiles/filedetails/?id=548705852

It looks a bit like copy/paste, tbh. But so far it is ok:
http://steamcommunity.com/sharedfiles/filedetails/?id=548705897
http://steamcommunity.com/sharedfiles/filedetails/?id=548705956

Only some houses are enterable, though.

All in all, the impression of Santa Catalina is good, but nothing special.

**Comment by karlkarl93** [comment]
I think Santa Catalina is a very well made map, it's very simple and should have more details and have some things fixed. The map is very open and small, so it's difficult to make some types of ops on. The main problems are it being small (which isn't always a bad thing), it's too plain (should have more stuff around the area, houses, maybe some random junk, anything) and it seems a little bit unfinished.

Here's an album on some of the better things: http://imgur.com/a/CqW1N
Here's an album on some of the more average things: http://imgur.com/a/YkF3l
Here's an album about some of the problems on the map: http://imgur.com/a/4oywQ

**Comment by Fourjays** [comment]
Rejected in the meeting on 29/11/15.
