### ISSUE TITLE
New Faction: Seals (Scuba)

### ISSUE THREAD

**Issue by TheGrandVizier** [blackwatchint/blackwatchint#48]
As the header says, would be really awesome to have scuba gear loadouts with re-breathers and all on the pedestals.

**Comment by adios113** [comment]
Labbeled.

**Comment by ShiFoo** [comment]
Should this also be available to eatern factions with AKs or is this NATO only?

**Comment by Fourjays** [comment]
I'm going to say NATO only for now.

**Comment by ShiFoo** [comment]
RTO has limited equipment due to size of backpack and rebreather as vest. AR uses M27 for a lightweight machine gun. Committed to feature branch.

**Comment by ShiFoo** [comment]
Merged and closed.
