### ISSUE TITLE
New Faction: Specops (Black Uni)

### ISSUE THREAD

**Issue by TheGrandVizier** [blackwatchint/blackwatchint#49]
As the title suggests, Specops, black uniforms, totally overpowered individual soldiers. :dart:

**Comment by ShiFoo** [comment]
i have made up my mind for blackops uniform because i am gonna use that in my editor mission. Can post an example later today. Dunno why they should be overpowered tho... :-)

**Comment by TheGrandVizier** [comment]
Historically speaking, we have always deployed to such missions in lower
playercounts. A sub can accommodate only 4 divers, so teams are limited to
four.
Once teams are limited to four and you still want to retain certain
capabilities in each team (AR, AT, CFR), the logical conclusion is to merge
roles under the "excuse" that these are "specops" or whatever.

Point being, the 4-man FT model limits abilities, to avoid this, a 4 man
team has to carry more in terms of weight. Weight also translates into
firepower and thus the word "overpowered", which  may have been used
liberally in this context.
Apologies, hope this is clearer.

**Comment by ShiFoo** [comment]
Draft committed to master

**Comment by ShiFoo** [comment]
I will think about adding one or two new roles tothis before i close it.

**Comment by ShiFoo** [comment]
Loadouts done
