### ISSUE TITLE
USMC & Bundeswehr - Additional Loadouts

### ISSUE THREAD

**Issue by blackwatchint** [blackwatchint/blackwatchint#55]

**Comment by adios113** [comment]
#28

**Comment by adios113** [comment]
What's the progress on it?

**Comment by ShiFoo** [comment]
Slow progress. Not happy with the crew/pilot loadouts yet. Will rethink about them. Otherwise working on it when there is nothing else to do.

**Comment by ShiFoo** [comment]
New role loadouts committed

**Comment by ShiFoo** [comment]
**Issues fixed: **
All Rotary Crewman +GPS
All Blufor Rotary Crewman programmable radio
US MMG replace M60 with M240B
UK rotary uniform RAF version
US DMR check mounted fleshlight, check suppressor, check pistol suppressor
US Army sniper OCP/UCP check sound suppressor
US Sniper bigger backpack
US DMR correct amount of ammo
GER Crewman new helmet "Crewman KSK helmet fleck/tropen"
UK Sniper check suppressor and mounted light
UK crewman new helmet "Crewman Helmet BAF"
UK rif missing pistol ammo
US RTO +1 mag

**Comment by Fourjays** [comment]
Can we get issues #101 and #102 applied to these loadouts in time for the planned milestone?
