### ISSUE TITLE
US Army & UK - Additional Loadouts

### ISSUE THREAD

**Issue by blackwatchint** [blackwatchint/blackwatchint#56]
#28

**Comment by ShiFoo** [comment]
US Army and UK loadouts committed to master.

**Comment by ShiFoo** [comment]
__Issues fixed:__
All Rotary Crewman +GPS
All Blufor Rotary Crewman programmable radio
US MMG replace M60 with M240B
UK rotary uniform RAF version
US DMR check mounted fleshlight, check suppressor, check pistol suppressor
US Army sniper OCP/UCP check sound suppressor
US Sniper bigger backpack
US DMR correct amount of ammo
GER Crewman new helmet "Crewman KSK helmet fleck/tropen"
UK Sniper check suppressor and mounted light
UK crewman new helmet "Crewman Helmet BAF"
UK rif missing pistol ammo
US RTO +1 mag

**Comment by Fourjays** [comment]
Reopening this as issues issues #101 and #102 affect these loadouts. Can we get them applied before the planned milestone?
