### ISSUE TITLE
BWMod v1.3.1

### ISSUE THREAD

**Issue by blackwatchint** [blackwatchint/blackwatchint#61]
v1.3
- added: UH Tiger
- added: Helipilot uniform
- added: Knighthelm
- added: integrated CBA Joint Rails (remove your BWA3_Comp_ASDG!)
- added: custom G27 / G28 silencer sounds
- added: MG4 and MG5 Tracer magazines
- added: modules to customize BW vehicles
- added: Fernspaeher (recon) sub faction
- added: other misc. soldier classes
- added: BW icon in Virtual Arsenal
- added: missing items to VA box
- added: TFAR BW radios to VA box
- changed: adjusted interaction positions on IFV Puma and MBT Leopard with ACE
- fixed: missing classes in Zeus
- fixed: wording in field manual for NaviPad (German)
- fixed: missing materials in FIRE geometry on MBT Leopard
- fixed: material effect with impacting rounds on all models
- fixed: smoke launchers weren't synched in MP
- fixed: IFV Puma doesn't fall over as easily when turning on high speeds
- fixed: IFV Puma ABM rounds with ACE FCS
- fixed: dragging and carrying BW boxes with ACE

http://www.armaholic.com/page.php?id=24147

**Comment by Fourjays** [comment]
An additional update to BWMod (v1.3.1) has been released that addresses the issues created by the Arma 3 1.54 update such as #111.

**Download:** http://www.armaholic.com/page.php?id=24147

**Comment by TheGrandVizier** [comment]
uploaded to repo

**Comment by Fourjays** [comment]
Update committed to the test modpack repository, changes awaiting deployment.
