### ISSUE TITLE
British SL and FL have radio backpacks.

### ISSUE THREAD

**Issue by blackwatchint** [blackwatchint/blackwatchint#63]
On the loadout boards, the British squad leader and fireteam leader spawn with radio backpacks. Should be non-radio backpacks.

**Comment by adios113** [comment]
Fixed, working properly.

**Comment by Fourjays** [comment]
Fixed with commits 9761301fc7f1fa512b2f1de2d57979a727de221d and 8a6cdeceb28bdf9cfa107dece50c8f64fa2f1a7b.
