### ISSUE TITLE
Technical analysis of Gorgona

### ISSUE THREAD

**Issue by blackwatchint** [blackwatchint/blackwatchint#66]
The map "Gorgona" needs a full technical analysis done to ensure that there are no issues with it.

**Comment by Andowrs** [comment]
So I tested this map out and it seems quite ok. The map is small and I did not have any fps issues on this map. http://steamcommunity.com/sharedfiles/filedetails/?id=562725138 

Gorgonas biggest town is Gorgona Scalo and just south of it, is Vila Margharita which is even smaller. There is a prison west of Gorgona Scalo and it has a very dumb gate that is blocked by a building. There is a military base on the south-west part of the island which includes a shooting range. The North-west of the island has a small scrapyard that is surrounded by a dense forest. On the south bottom of the island you will the second military base, but it's smaller compared to the one on the south-west.
http://steamcommunity.com/sharedfiles/filedetails/?id=562725047 
http://steamcommunity.com/sharedfiles/filedetails/?id=562725099
http://steamcommunity.com/sharedfiles/filedetails/?id=562725120
http://steamcommunity.com/sharedfiles/filedetails/?id=562725061
http://steamcommunity.com/sharedfiles/filedetails/?id=562725056
http://steamcommunity.com/sharedfiles/filedetails/?id=562725031
http://steamcommunity.com/sharedfiles/filedetails/?id=562725038
http://steamcommunity.com/sharedfiles/filedetails/?id=562725072
http://steamcommunity.com/sharedfiles/filedetails/?id=562725089

I think it is a good map, although I think it would only be good for a small scale op. The landscape is beautiful and I had no issues with the map. Almost all of the house are entrable.

**Comment by karlkarl93** [comment]
I didn't have any technical issues with the map, it worked nicely and had a good performance.
The map itself looks very nice, I really like the look and feel of the map.

http://imgur.com/a/2bg08

The map is small but it has hills and forest so it isn't that open. It's sort of stratis-like, but different.

**Comment by Fourjays** [comment]
Analysis was concluded and this map will be remaining in the modpack.
