### ISSUE TITLE
Technical Analysis of Bastogne

### ISSUE THREAD

**Issue by blackwatchint** [blackwatchint/blackwatchint#67]
The map "I44: Battle of the Bulge" needs a full technical analysis done to ensure that there are no issues with it.

**Comment by wingatex** [comment]
Map is small only good for one time op and all you can see is the edge of the map

**Comment by karlkarl93** [comment]
This is a very tiny, wintery chernaruseque map.

**Comment by Fourjays** [comment]
This map is quite literally an Arma 2 map that works in Arma 3 without issue. As already said it does have a nice atmopshere and feel, but it is very very small. As it is an Arma 2 map most the buildings can't be used.

Performance is good and aside from some poor texture work it is free of technical faults.

http://steamcommunity.com/sharedfiles/filedetails/?id=565028944
http://steamcommunity.com/sharedfiles/filedetails/?id=565029107
http://steamcommunity.com/sharedfiles/filedetails/?id=565029014
http://steamcommunity.com/sharedfiles/filedetails/?id=565029362

**Comment by Fourjays** [comment]
Was decided to remove this map in the meeting on 29/11/15 and an action has been created with #103.
