### ISSUE TITLE
New Faction - Taliban

### ISSUE THREAD

**Issue by blackwatchint** [blackwatchint/blackwatchint#68]
New Faction for loadout stands representing the Taliban.

* Squad Leader
* Fireteam Leader
* Radio Transmitter Operator
* Corpsman
* Engineer
* Combat First Responder
* Automatic Rifleman
* Assistant Automatic Rifleman
* Rifleman (AT)
* Heavy Machine Gun
* Designated Marksman
* Sniper
* Demolition Man
* Crewman
* Rifleman

**Comment by TheGrandVizier** [comment]
This is pretty straight forward. All gear Russian and russian captured.
UN-standardized uniforms / hats / helmets.
Vests with low protection and low inventory (bandoleer?)
Large backpacks, survival gear for the Harsh geographic conditions of Afghanistan :)

**Comment by ShiFoo** [comment]
AK 12 which we currently use for russian loadouts or real AK-74's? I think as Taliban you are not supposed to have holosights :-)

**Comment by TheGrandVizier** [comment]
Yes. No attachments but flashlight.

**Comment by ShiFoo** [comment]
New faction merged to develop. Closing.
