### ISSUE TITLE
New Faction - ISIS

### ISSUE THREAD

**Issue by blackwatchint** [blackwatchint/blackwatchint#69]
New Faction for loadout stands representing the ISIS.

* Squad Leader
* Fireteam Leader
* Radio Transmitter Operator
* Corpsman
* Engineer
* Combat First Responder
* Automatic Rifleman
* Assistant Automatic Rifleman
* Rifleman (AT)
* Heavy Machine Gun
* Designated Marksman
* Sniper
* Demolition Man
* Crewman
* Rifleman

**Comment by Fourjays** [comment]
Rejected in the meeting on 06/12/2015.
