### ISSUE TITLE
New Faction - FSA

### ISSUE THREAD

**Issue by blackwatchint** [blackwatchint/blackwatchint#70]
New Faction for loadout stands representing the FSA.

* Squad Leader
* Fireteam Leader
* Radio Transmitter Operator
* Corpsman
* Engineer
* Combat First Responder
* Automatic Rifleman
* Assistant Automatic Rifleman
* Rifleman (AT)
* Heavy Machine Gun
* Designated Marksman
* Sniper
* Demolition Man
* Crewman
* Rifleman

**Comment by adios113** [comment]
What is "FSA"?

**Comment by ShiFoo** [comment]
Free Syrian Army?

**Comment by TheGrandVizier** [comment]
As discussed previously, FSA will be standing in for any Western-armed / trained guerrillas. 
They should sport a semi-coherent uniform, coherent vests and helmets, Vests probably low-protection.
Weapons should be in line with Western armies, minus Lasers, NVGs and Tablets. Androids are probably OK, as everyone has one these days in that part of the world.
This is how I think we should go about it for now.

IF we desire a much more realistic take on this organization, that will also include inconsistencies in armament between different teams and members of teams.
Here is a link to a list of what the FSA actually uses: https://en.wikipedia.org/wiki/List_of_military_equipment_used_by_Syrian_opposition_forces I'll save you the click: They use whatever they can get their hands on, and it is quite evident that they are not limited to american arms alone. Most of their Russian arms have been stolen or captured from the Syrian Army, or was brought in by defectors early in the war.

the more "realistic" FSA squad would be diverse in weaponry. I'd assume SLs/FTLs would sport M4s, while lower tier combatants would have to make do with old AK's.
Stands to reason AR's would be american M249s, and RPG's russian for disposables, while the heavier stuff are TOWs, for the most part, so need to be assmebled (do we even have any?).

Up to you which FSA "version" you prefer, but I think lets stick to basics for now.

**Comment by ShiFoo** [comment]
changes merged to develop. Closing.

**Comment by adios113** [comment]
Conflict issue with https://github.com/blackwatchint/blackwatchint/issues/233.
Faction is utilising Leighs Pack Uniforms. Same as https://github.com/blackwatchint/blackwatchint/issues/22. We probably will need to check the other factions.

**Comment by ShiFoo** [comment]
The FSA faction was implemented before it was 100% decided that LOP needs to be removed. Even though i agree that this faction is referencing LOP and we need to change it, i would like to handle it in another issue. This one was about creating the faction which has been completed.
