### ISSUE TITLE
Remove PromanView

### ISSUE THREAD

**Issue by blackwatchint** [blackwatchint/blackwatchint#76]
Following an officer's meeting it was decided to remove the "PromanView" mod as it breaks default functionality in the game for adjusting the zoom in vehicles.

**Comment by Fourjays** [comment]
This issue will be on hold until #71 is closed at which point it will probably be made an optional mod.

**Comment by Fourjays** [comment]
Has been committed and deployed to the optional repository. Now removed from the live repository.
