### ISSUE TITLE
Adjust CFR/Corpsman medical quantities

### ISSUE THREAD

**Issue by blackwatchint** [blackwatchint/blackwatchint#77]
Medical quantities need adjusting to include more elastic bandages and fewer basic/QuikClot bandages.

**Comment by ShiFoo** [comment]
My idea would be to swap quantaties of field dressings with elastics. 

__CFR:__
Field Dressing: 10 -> 5
Elastic Badage: 5 -> 10
Packing Bandage: 10 (no change)
Quickclot: 5 ( no change )

__Corpsman:__
Field Dressing: 15 -> 5
Elastics Bandage: 5 -> 15
Packing Bandage: 15 ( no change )
Quickclot: 10 -> 5

I am currently thinking about lowering the corpsman amounts from 15 to 10. Not sure though, Thoughts?

**Comment by Fourjays** [comment]
Was agreed in a meeting to avoid going in-depth on the tweaks until #10 is fixed. I think your suggestion for making it 10/15 elastic bandages and 5/5 field dressing is probably fine for now though.

**Comment by ShiFoo** [comment]
Changes committed to master
