### ISSUE TITLE
Gunkizli

### ISSUE THREAD

**Issue by blackwatchint** [blackwatchint/blackwatchint#78]
**Description:**
The map is a 20 x 20 km plain.

Main features :
More than 100 villages and hamlets, 3 Airfields, heavy wood cover and vast expanses of shalow marshes.

**Download**: http://www.armaholic.com/page.php?id=29527
**Size:** 226MB

**Comment by CervenBWI** [comment]
The amount of urban terrain makes me question if this won't end up being another lagfest.

**Comment by karlkarl93** [comment]
In my tests it seemed fine, it may sound like a lot but those 100 urban areas are spread around the map, it's mostly wilderness.

**Comment by wingatex** [comment]
Map is pretty empty, has a lot of woodland areas but think it fits a niche what we don't have yet. Seemed to work fine and didn't find any major issues with the mod and all of ours appear to work with it is well. For 200mb cant really go wrong.

http://steamcommunity.com/sharedfiles/filedetails/?id=567945892
http://steamcommunity.com/sharedfiles/filedetails/?id=567947248
http://steamcommunity.com/sharedfiles/filedetails/?id=567947369
http://steamcommunity.com/sharedfiles/filedetails/?id=567947472
http://steamcommunity.com/sharedfiles/filedetails/?id=567947696
http://steamcommunity.com/sharedfiles/filedetails/?id=567947836

**Comment by Kentersnoodlefactory** [comment]
For the 200mb i guess give it a shot, has some interesting areas, it would nice for tanks. But it has quite a bit of vegetation for infantry to move around aswell, it looks nice and i think it would be nice addition to the map pool.

**Comment by Fourjays** [comment]
Rejected in the meeting on 06/12/2015.
