### ISSUE TITLE
Hindu Kush

### ISSUE THREAD

**Issue by blackwatchint** [blackwatchint/blackwatchint#79]
**Description:**
Large 20x20km mountain terrain with multiple locations and possibility for combat scenarios.

Locations to date :
Abandoned Airfield
Destroyed Airfield
2 x Army Camp
8 x FOB
17 x Villages
2 x Towns
Lumbermill
Stone Quarry
Beverage Factory
Tora Bora Cave Complex (3km of underground corridors and spaces)
2 x other cave complex
6 x Heroine Plantations
Multiple enemy camps, small local farms, and other unique locations

**Download**: http://www.armaholic.com/page.php?id=28913
**Size:** 1.4GB

**Comment by CervenBWI** [comment]
I like the amount of multi-usage this map might be able to bring us in terms of op development. I guess we'll see if the size of the map itself is worth it in terms of performance.

**Comment by wingatex** [comment]
Map works fine without issue and works fine with all of our mods. No errors found with the map its self as it is 95% hills and trees. For the size i don't feel it adds anything, their isn't a lot of roads on the map so it is almost inaccessible and some places don't have any at all and with the tress and mountains it would be a nightmare. Their inst a lot on the map at all. In my opinion its a no.

http://steamcommunity.com/sharedfiles/filedetails/?id=569601719
http://steamcommunity.com/sharedfiles/filedetails/?id=569601682
http://steamcommunity.com/sharedfiles/filedetails/?id=569601650
http://steamcommunity.com/sharedfiles/filedetails/?id=569601617
http://steamcommunity.com/sharedfiles/filedetails/?id=569601551
http://steamcommunity.com/sharedfiles/filedetails/?id=569601518
http://steamcommunity.com/sharedfiles/filedetails/?id=569601471
http://steamcommunity.com/sharedfiles/filedetails/?id=569601441

**Comment by Kentersnoodlefactory** [comment]
I did look at this map, somehow i forgot to comment on it though o.O Ah well.. I agree it is way to plain and boring, not many interesting spots, and it doesn't look that high detail either.. No from me

**Comment by Fourjays** [comment]
Rejected in the meeting on 06/12/2015.
