### ISSUE TITLE
Orshanets (Ukraine)

### ISSUE THREAD

**Issue by blackwatchint** [blackwatchint/blackwatchint#80]
**Description:**
Terrain is based on real geographical data, combines two areas in Ukraine. However, it has nothing to do with real life Orshanets village, aside from the name, it is completely different area. 
Project in general IS NOT RELATED to situation in Ukraine IN ANY WAY. 

**Download:** http://www.armaholic.com/page.php?id=26807
**Size:** 684MB

**Comment by ShiFoo** [comment]
First of all: This map will not have my vote. The reason for that is: its too much work-in-progress.

The two towns look nice and detailed:
http://steamcommunity.com/sharedfiles/filedetails/?id=568777154
http://steamcommunity.com/sharedfiles/filedetails/?id=568777193
http://steamcommunity.com/sharedfiles/filedetails/?id=568777247
http://steamcommunity.com/sharedfiles/filedetails/?id=568777334
http://steamcommunity.com/sharedfiles/filedetails/?id=568777532

But essentially 90% of the map look like a low-res image of google earth:
http://steamcommunity.com/sharedfiles/filedetails/?id=568777387
http://steamcommunity.com/sharedfiles/filedetails/?id=568777450
http://steamcommunity.com/sharedfiles/filedetails/?id=568777624 ( these are not actually houses, its texture)
http://steamcommunity.com/sharedfiles/filedetails/?id=568777503

Result: Too much WIP. Not suitable for our mappack.

**Comment by Fourjays** [comment]
Doesn't look like a lot has changed since I last looked at it. I think we'll put this suggestion on hold until it has had some updates.

**Comment by Fourjays** [comment]
Rejected in the meeting on 06/12/2015.
