### ISSUE TITLE
Chernobyl Zone

### ISSUE THREAD

**Issue by blackwatchint** [blackwatchint/blackwatchint#81]
**Description:**
The Chernobyl Zone works with Arma 2 or Arma 3.
Abandoned place in northern Ukraine.

**Download:** http://www.armaholic.com/page.php?id=21332
**Size:** 1.3GB

**Comment by karlkarl93** [comment]
This map is a mixed bag. The biggest problem is that you cannot enter most of the buildings and the ones you can enter only have one corridor with a few rooms on a random floor but there are a few buildings that were entierly enterable. While the rooms look good, there are very few of them. 

There's a trainyard on the map which is ok-looking. It has a few repetative looking places but it doesn't look too bad, it has a very nice train station building and a look-out tower. Other than that there's nothing special.

The nuclear reactor is the worst part about the map. While it does look like the real life equivalent, none of the building are enterable and the textures of the buildings look down right ugly.

http://imgur.com/a/9KmKG - Screenshots I took.

In my opinion, this map isn't made well and we shouldn't add it to our modpack.

**Comment by Fourjays** [comment]
I tested this in November, and will add that there are numerous glitches (such as people/vehicles sinking into raised patios) and a good 60-70% of the map is currently empty.

**Comment by Fourjays** [comment]
Rejected in the meeting on 03/01/2016 due to quality and work-in-progress status.
