### ISSUE TITLE
FSF Al Rayak

### ISSUE THREAD

**Issue by blackwatchint** [blackwatchint/blackwatchint#83]
**Description:**
I'm pleased to present my latest terrain for Arma 3 : Al Rayak.
The map is 20 x 20 km, and aims at loosely representing a middle eastern country.

40 km of coastline, 7 cities, 3 seaports, 2 main rivers, 4 airfields, about 100 villages, many bridges, and far more trees than would be here in reality.
The vegetation is mostly a placeholder and will be updated in the future. I also plan to add many rock formations to give the whole area a more arid and mountaineous feeling.

**Download:** http://www.armaholic.com/page.php?id=28564
**Size:** 267MB

**Comment by karlkarl93** [comment]
This is a large map of a mountainous, watery area.

http://imgur.com/a/IQD4G

The map is pretty well made, some of the bigger cities look somewhat similar but they are well made. The bigger problem is the buildings which cannot be entered.

**Comment by wingatex** [comment]
Map is fine an works with all our mods, no issues performance wide and no major errors found other than blending or roads etc. Map is lacking in the "wow" factor as it feels almost familiar as some places looked copied out of Takistan onto this and just changing of the ground. Not worth in my opinion.

http://steamcommunity.com/sharedfiles/filedetails/?id=569590966
http://steamcommunity.com/sharedfiles/filedetails/?id=569589604
http://steamcommunity.com/sharedfiles/filedetails/?id=569589604
http://steamcommunity.com/sharedfiles/filedetails/?id=569599517
http://steamcommunity.com/sharedfiles/filedetails/?id=569599787
http://steamcommunity.com/sharedfiles/filedetails/?id=569600094

**Comment by Fourjays** [comment]
Rejected in the meeting on 06/12/2015.
