### ISSUE TITLE
Pianosa

### ISSUE THREAD

**Issue by blackwatchint** [blackwatchint/blackwatchint#84]
**Description:**
Pianosa is an real italian island, which i used as guide for this terrain, but the terrain is still heavily modified for gaming purposes.

The island is ~10km² big and is relativly flat, not a big surprise, because pianosa is italian for flat.
Well, long story short: This is the Alpha Version 0.1, I hope you like it and if not, PLEASE tell me so! So I can improve it for everyone!

Background: 
In the year 2035 the situation in southern europe is getting more precarious then ever before. To help the struggeling south-european countries the EU subventioned them, Italy used that money to improve living conditions on smaller peripheral island and started some new projects on island like Pianosa, e.g. the construction of a new city, the installation of some solar power plants (more to come). Because of the strong wave of refugees from north africa, there are several slum-areas scattered over the island, even in old and historic places like the abandoned prison complex in the center of the island. 

**Download:** http://www.armaholic.com/page.php?id=28418
**Size:** 193MB

**Comment by karlkarl93** [comment]
This is a small island map with a town, military outpost, an airfield and a sea-base thing.

Screenshots - http://imgur.com/a/neTYf

The map is pretty well made and I got nothing to complain about.

**Comment by abelarno** [comment]
The roads in the towns are too tight for the AI to drive trough. They will hit buildings and stop.
The towns are pretty nice for CQB, and they have some nice spots, but the rest of the island doesn't offer much different than what can be found on Altis. It is also sloppy made in places. It seems to expect basketbal spectators to have binoculars (http://images.akamai.steamusercontent.com/ugc/400056914976379842/14E052753A7E379564511678121B96808329F3B9/), and walls are clipping trough the ground at places (http://images.akamai.steamusercontent.com/ugc/400056914976380344/2B90A7A4E22C1AECA1261A9C20B9FF7D8CE6B164/).

The oilrig is a nice touch, but it needs more work in zeus to make it interesting.

The island is too small for any army vs army operation in my opinion. It could work for infiltration and stealth missions tough.

Besides the AI not able to drive on town roads, the maps works fine from a technical perspective, but I don't believe its quite ready to be used in game.

**Comment by ShiFoo** [comment]
I had a look myself and, frankly, i am torn about this map. On one side i quite like the setting and the design. The towns look natural, it has some hotspots for ops and the quality is good so far. On the other side, I had one issues with flickering piles of log and we already have quite a good amount of island maps. This would be another map which is good for a second op but not for main op. If we ever do a mapcycle i would like to see it in there. But in my opinion, we currently do not need another island map...

**Comment by Fourjays** [comment]
Rejected in the meeting on 03/01/2016 due to quality concerns.
