### ISSUE TITLE
Diaoyu Islands

### ISSUE THREAD

**Issue by blackwatchint** [blackwatchint/blackwatchint#86]
**Description:**
Diaoyu Islands is a 25.6km x 25.6km terrain project.(N25.97,E123.427 to N25.7,E123.716)
Based on real terrain geographic information data, created for RV4 ArmA3.
Islands specifics is purely fictitious and any similarity is purely coincidental.

**Download:** http://www.armaholic.com/page.php?id=21134
**Size:** 174MB

**Comment by ShiFoo** [comment]
i had a quick look at this map. In one word: boring.
The main island is essentially "one big rock full trees".
It has no hotspots, no nothing. It doesn't have any visual flaws but its just suitable for our ops..

Definitly a NO from me.

**Comment by karlkarl93** [comment]
This map is basically 20 km² of sea, a few rocks and 3 islands.

http://imgur.com/a/unUf2 - Screenshots.

I took screenshots of every bit of land that map had, there wasn't a lot. The emptiness of the map allows the zeus to build his own things (potential military bases and players attacking them like in D-Day) but that's about it.

**Comment by Fourjays** [comment]
Rejected in the meeting on 03/01/2016 due to quality concerns.
