### ISSUE TITLE
Mission Enhanced Little Bird (MELB)

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/blackwatchint#88]
**Description:**
I would like to officially introduce sykoCrazy's and I current project the [MELB] Mission Enhanced Little Bird. A project we have been working on and off for a few months. 

Since the model is finally taking shape, we would like to share a little teaser with the community. What has taken the most amount of time is getting all of the most current pictures, weapons, and capabilities to begin to create the most accurate helicopter our abilities will allow.

This project is meant to represent the latest and most current version of the MH-6M and AH-6M special operations helicopter.

**Download:** http://www.armaholic.com/page.php?id=28856
**Size:** 55MB

**Comment by Kentersnoodlefactory** [comment]
Very nice mod, High detail the exterior looks amazing there are several variants, interior even has a toggable screen for spotting and such. Nice flight model, works well with AFM, all in all a great mod would definately like to see it implemented. AND we can finally get rid of that disgusting green colour of the current mh6's :P

**Comment by Kentersnoodlefactory** [comment]
Fail...

**Comment by ShiFoo** [comment]
v0.00003 Hotfix
Fixed:
- Sling loading works again!
- Instrument gauge dials easier to see
Tweaked:
- Damage model 
- Hellfire damage radius 
- Helicopter sound
- Various optimization tweaks
- Easter egg now easier to activate(action menu)
Removed:
- TOW functionality from guided rockets since ACE3 lasers work again.
So now even when using ACE you can lock onto laser, cycle to desired rocket, lock on and fire! 
http://www.armaholic.com/page.php?id=28856

**Comment by Fourjays** [comment]
This is a really nice helicopter pack. Detailed models, good interiors, some new functionality (TOW launchers). Sounds are amazing. The helicopters handle really nice as well, feel slightly more controllable than the default Littlebirds without feeling fake. I didn't get a chance to go too into detail on the flight model, so still need to checkout some elements of the handling.

**Comment by TheGrandVizier** [comment]
Uploaded to repo

**Comment by Fourjays** [comment]
Had an issue with @wingatex last night where this bounced when landing at -14m/s rather than taking damage. I subsequently performed a rough landing and took substantial damage. Want to do some further testing to determine the extent of this random invulnerability.

**Comment by Kentersnoodlefactory** [comment]
Tested this, couldn't get it to bounce? It hit the ground hard and took damage, did this in both vrs state, hitting the ground with full collective and no collective, did this but more as a normal landing. Only type of bounce i got was the small occasional bounce due to the heli having skids.

**Comment by Fourjays** [comment]
Okay, sounds like it was a minor glitch rather than the normal.

**Comment by Fourjays** [comment]
Committed to the test modpack repository and ready for deployment.
