### ISSUE TITLE
Chernarus Winter

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/blackwatchint#90]
**​Description:**
This terrain is the winter version of Chernarus for A3. Prepare to fight in the snow. An advice, don't forget your warmest uniform!

**Download:** http://www.armaholic.com/page.php?id=29752
**Size:** 595MB

**Comment by karlkarl93** [comment]
I gave this map a quick look and it looks good, all they did was replace the green ground with a white snow texture and make the trees whiter, as if they were snowy.

I didn't have any FPS issues and it worked fine with the modset.

**Comment by ShiFoo** [comment]
I see Winter Camo, maybe we can extract it? http://www.armaholic.com/page.php?id=29845

**Comment by wingatex** [comment]
Yes the mod works how it should do with no issues like the other chernarus maps. The mod looks visual good and feels like a different map being textured this way. We don't have a winter map at this time so i feel it is worth having as it gives us something else to use and play with. All mods seem to be working fine on it.

**Comment by wingatex** [comment]
http://steamcommunity.com/profiles/765611980

**Comment by wingatex** [comment]
http://steamcommunity.com/sharedfiles/filedetails/?id=567651288
http://steamcommunity.com/sharedfiles/filedetails/?id=567651284
http://steamcommunity.com/sharedfiles/filedetails/?id=567651261
http://steamcommunity.com/sharedfiles/filedetails/?id=567651234
http://steamcommunity.com/sharedfiles/filedetails/?id=567650819

**Comment by Kentersnoodlefactory** [comment]
It's a nice map, as Ryan said it looks nice. It is still chernaurus, but it does feel different. If we had some winter camo this map would be really nice! Mods work on it haven't had any issues and it has good fps.

**Comment by TheGrandVizier** [comment]
Uploaded to repo

**Comment by Fourjays** [comment]
Were some issues last night with both @TheGrandVizier and @wingatex getting missing CAData errors relating to this map. Both were able to resolve them, but want to double check and make sure these were local issues before closing.

**Comment by Fourjays** [comment]
Committed to the test modpack repository and awaiting deployment.
