### ISSUE TITLE
IR grenades need to be faction dependent

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/blackwatchint#92]
The IR grenades in all loadouts are currently the NATO variant. This is fine for visual uses (i.e. marking an LZ), but will cause problems for lock-on weaponry. OPFOR and Independent forces need their faction specific variant for their own IR weaponry to be able to lock-on to the IR grenade as a target.

**Comment by ShiFoo** [comment]
Change committed to feature branch.

**Comment by ShiFoo** [comment]
Branches merged. Closing.
