### ISSUE TITLE
Bundeswehr Tornado

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/blackwatchint#93]
**Description:**
This adds the Bundeswehr Tornado.
It works together with the BW-Mod. What means that the plane will get added to the BLUFOR\Bundeswehr faction.
If you don't have the BW-Mod the faction will be created.

**Download:** http://www.armaholic.com/page.php?id=25898
**Size:** 30MB

**Comment by karlkarl93** [comment]
I spawned the craft, got inside it and it seemed to work fine, it may even work with the USS Nimitz.

**Comment by Fourjays** [comment]
Gave this a go while going through a bunch of other planes. It is kind of buggy and unfinished. None of the gauges work, weaponry makes no noise at all and the performance feels sluggish.

**Comment by Fourjays** [comment]
Rejected in the meeting on 13/12/15 due to poor quality.
