### ISSUE TITLE
Valtatie 5 (VT5)

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/blackwatchint#94]
**Description:**
Name of the map is Valtatie 5, or "VT5", and it translates to "Highway 5". I've been working it about a year now and with the help I've had its beginning to be ready for releasing. The map is still work in progress.

**Download:** http://www.armaholic.com/page.php?id=28984
**Size:** 152MB

**Comment by CervenBWI** [comment]
I'll want to know precisely how much of a WIP this actually is.

**Comment by Fourjays** [comment]
I've only gone over it briefly, but I've yet to see where it is WIP. There's no obvious "empty" spots.

**Comment by karlkarl93** [comment]
The WIP part may be the placement of some buildings, I guess the author wants to make the map look better in some parts (like the gas station in the picture album below). 

Since I live in an area like that in real life, this does look realistic.

http://imgur.com/a/rri1b

**Comment by wingatex** [comment]
Map seems good, no issues found with my test. Seems like it offers something different with a lot of fun areas for different types of operations. Mods work fine on the map. For the size of the mod I feel it is worth having in the mod pack.

http://steamcommunity.com/sharedfiles/filedetails/?id=567958367
http://steamcommunity.com/sharedfiles/filedetails/?id=567958474
http://steamcommunity.com/sharedfiles/filedetails/?id=567958574
http://steamcommunity.com/sharedfiles/filedetails/?id=567958674
http://steamcommunity.com/sharedfiles/filedetails/?id=567958772
http://steamcommunity.com/sharedfiles/filedetails/?id=567958887

**Comment by Kentersnoodlefactory** [comment]
Very nice map, makes me feel at home a bit :D Very scandinavia, looks good nice dense forests and interesting areas, +1 for me! Has good frames aswell.

**Comment by TheGrandVizier** [comment]
Uploaded to repo

**Comment by Fourjays** [comment]
Added to the test modpack repository, changes awaiting deployment.
