### ISSUE TITLE
Sugar Lake

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/blackwatchint#95]
**Description:**
Sugar Lake is a township in the Vieilhomme Delta. A hub for oil exploration and extraction, Sugar Lake has extensive port facilities servicing a number of oil rigs and refineries in the surrounding wetlands. These include the Sugar Lake Oil Field, owned and operated by Vrana Petrochemicals, a division of the multinational conglomerate Vrana Industries.

**Download:** http://www.armaholic.com/page.php?id=29789
**Size:** 143MB

**Comment by karlkarl93** [comment]
This is a well made map with a few problems.

http://imgur.com/a/rqia9

Excluding that one small problem this map is well made and has great industrial areas.

**Comment by wingatex** [comment]
Love it, i want. mod works fine, haven't found any issues with the mod and works with our current mods we have. Had good frames throughout and parts of the map looked stunning, hope to see some pretty awesome missions with this map. Can see a lot of boat inserts with that in mind and good industrial areas which a lot of maps don't provide.

http://steamcommunity.com/sharedfiles/filedetails/?id=567688853
http://steamcommunity.com/sharedfiles/filedetails/?id=567689081
http://steamcommunity.com/sharedfiles/filedetails/?id=567689290
http://steamcommunity.com/sharedfiles/filedetails/?id=567689489
http://steamcommunity.com/sharedfiles/filedetails/?id=567689667
http://steamcommunity.com/sharedfiles/filedetails/?id=567689826
http://steamcommunity.com/sharedfiles/filedetails/?id=567690089
http://steamcommunity.com/sharedfiles/filedetails/?id=567690335
http://steamcommunity.com/sharedfiles/filedetails/?id=567690502

**Comment by ShiFoo** [comment]
I can only agree with Ryan. That map is really really interesting! This opens up a some opportunities for infantry combat. i would really like to see this in the map pool!

**Comment by TheGrandVizier** [comment]
Uploaded to repo

**Comment by Fourjays** [comment]
Added to the test modpack repository, changes awaiting deployment.
