### ISSUE TITLE
Antonov AN-2

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/blackwatchint#97]
**Description:**
This addon adds some An-2 variations to Arma 3. Some are made up and some resemble a random selection of real planes.

**Download:** http://www.armaholic.com/page.php?id=27812
**Size:** 86MB

**Comment by karlkarl93** [comment]
I tested it a little bit, didn't fly one but I spawned the different variants. They all looked good and I didn't see any problems.

**Comment by Fourjays** [comment]
The Antonov An2 is a nice little biplane. This one is well made, seems to fly pretty well and accurately as far as I can tell. I'm not sure what it really provides us other than being the closest thing we'll get to an OPFOR transport aircraft. It looks like it can fit 12 people in the rear (and 2 pilots) so isn't too unreasonable for a paradrop, just can't compete with a C130.

http://steamcommunity.com/sharedfiles/filedetails/?id=569682264
http://steamcommunity.com/sharedfiles/filedetails/?id=569682392
http://steamcommunity.com/sharedfiles/filedetails/?id=569682438

**Comment by Fourjays** [comment]
Accepted in the meeting on 13/12/15.

**Comment by Fourjays** [comment]
Added to the test modpack repository, changes awaiting deployment.
